### ISSUE TITLE
losing inventory when logging out

### ISSUE THREAD

**Issue by toodles123** [NillerMedDild/Enigmatica2Expert#1000]
current modpack version and past versions

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

i have completely lost my inventory when i have logged off at least five times. I am not sure how many times this has happened as I completely empty my inventory before logging off. When I don't remember to do this it is apparent that I have lost everything. I  chose to allow cheats when I started this mod pack. However, the pack will not allow me to change my game mode to replace lost items. This is very frustrating as tinkers tools take a long time to level up.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Man that sucks. If the game doesn't allow you to cheat, you can open to LAN and enable cheats that way. There's a command for leveling Tinker tools.

Is your world saving correctly?

**Comment by Dimentive** [comment]
You should probably provide a log (located: `%userprofile%\Documents\Curse\Minecraft\Instances\Enigmatica 2: Expert\logs\latest.log` on Windows).

Also, do you have any backups? FTB Utilities, one of the mods in this modpack, has a backup feature which is enabled by default. This saves a backup of your world every two hours (if unchanged). You can configure how frequently it saves backups, how much it compresses them (if at all), how many backups it should keep before deleting old ones, how big the backups folder can possibly get before it starts deleting old backups, and more in the `ftbutilities.cfg` file (located: `%userprofile%\Documents\Curse\Minecraft\Instances\Enigmatica 2: Expert\config\ftbutilities.cfg`. Changes to the config are only effective on the server-end if you’re playing multiplayer.

If it’s been saving backups, you’ll find them in the “backups” folder in your modpack’s root folder, where you can copy a backup and replace your world save (in the “saves “folder of your modpack’s root folder) with it to restore a backuped world. If you haven’t had backups enabled by now, you can use commands to get your items back by opening your world to LAN and setting “Cheats” to “On,” like Niller said, but I do recommend enabling backups in case anything bad happens to your world again in the future.

**Comment by MaxNeedsSnacks** [comment]
Does the console spit any errors out or anything?

**Comment by Krapht** [comment]
Another way to cheat items (if you have enabled cheats) is to ctrl-click the JEI/NEI config icon (it should turn red) and then just search and click the items you want and it will be /given to you

I'm curious, when you log back in, do you start in the same spot as you logged out, or do you start back att world Spawn?

**Comment by blackgunter** [comment]
I'm having a similar issue. In my SP world, when I log out and log back in my character is in a different location with a previous instance of my inventory. Everything else in the world is the same, anything I've built is still there and if I put my inventory in a chest before I log out its still there. It also does not happen every time I log back in.

To try fix it I checked the .invo files in my instance folder and realised there was both my own inventory file "Blackgunter.invo" and one called "_StupidestPlayer.invo". My Mekanism machines also recognised me as both "StupidestPlayer" and "Blackgunter" as the owner on different occasions. I've also had my name come up as StupidestPlayer in the text log when I manually start a Backup. This started happening once I repaired my EE2 instance after my twitch launcher broke and I had to reinstall it. I was wondering if it is some sort of anticheat mechanic? I feel like I'm in some CreepyPasta :'(

**Comment by genericfutureman** [comment]
I have the same issue as @toodles123. I have had the issue E2 and E2E.

**Comment by NillerMedDild** [comment]
Well that's concerning @blackgunter - Does deleting the `_StupidestPlayer.invo` file remedy the issue?
@toodles123 and @genericfutureman could you check if your world has a similar file? It should be in `saves/worldname/playerdata`

**Comment by thraaawn** [comment]
I just decompiled all the mods in the pack. None of them contain the string "stupidest".

**Comment by NillerMedDild** [comment]
Really, all of them? Was your search case sensitive?
Either way, the string wouldn't have to be hard-coded, there are tons of ways to hide it a bit.

**Comment by thraaawn** [comment]
Yupp, I've written a short bash script a while ago that deobfuscates and decompiles a mods folder to be able to search through it. I did a 'grep -inr stupidest .', i.e. case insensitive, recursive. Looking for "stupid" yielded more results, but none of them are related in any way.

And yes, it would be easy to obfuscate, so this does not proof anything of course.
But it puts a bit more emphasis on this:
> This started happening once I repaired my EE2 instance after my twitch launcher broke and I had to reinstall it.

It sounds like the game is being started with a badly chosen placeholder for the username.

**Comment by genericfutureman** [comment]
I am also showing two .invo files. One is named after my user name and one is named after my old user name.

**Comment by genericfutureman** [comment]
> 
> 
> Well that's concerning @blackgunter - Does deleting the `_StupidestPlayer.invo` file remedy the issue?
> @toodles123 and @genericfutureman could you check if your world has a similar file? It should be in `saves/worldname/playerdata`

While I was searching the issue on Google, I noticed that @blackgunter also posted on Reddit. Someone asked what happens when he/she deletes the stupidestplayer.invo file and he/she responded, "I've tried deleting it and it solves the problem for a short while, but then it comes back. I was wondering if it was an issue with anti cheat and going afk, but I have not tested that theory yet."

Hopefully that helps.

**Comment by NillerMedDild** [comment]
Recap:
The issue seems to be caused by having two playerdata files that share UUID, but what actually generates the extra file is a mystery.

**Comment by genericfutureman** [comment]
I am going to attempt to manually manage the file until a fix is found. I know nothing about coding but I will try to provide some behavior for when the extra file is generated.

**Comment by NillerMedDild** [comment]
Great, thank you.

**Comment by blackgunter** [comment]
@NillermedDild Here is a link to that reddit post I created to try fix my problem (https://www.reddit.com/r/feedthebeast/comments/b2plue/enigmatica_2expert_inventory_is_resetting_to_a/) @genericfutureman thank you for helping out. Sorry I'm in Europe and have been at work and couldnt respond.

Here is some more details I've discovered since yesterday....

I started up my instance again after deleting "StupidestPlayer.invo" yesterday evening and this happened (https://imgur.com/gallery/3affPYf).

Long story short when I first logged in i was logged in as Stupid, then I literally saved and exited to the main menu and opened my world again and I was Blackgunter. I did this 4 times and I was my own "Blackgunter" profile the whole time.

I then tried to troubleshoot my inventory being lost by putting some blocks in my inventory and restarting minecraft. The same thing happened (https://imgur.com/gallery/5eZap13), but this time my inventory was retained. 

Also, I should mention that I had cheats activated when i created the world, but on several occasions but they have been deactivated randomly, similar to the original poster. 

> I chose to allow cheats when I started this mod pack. However, the pack will not allow me to change my game mode to replace lost items. 

For example, randomly I could not use the teleport function in Journeymaps. I believe that this was due to me being logged in as the other account, which would not have had cheats enabled by default.

**Comment by MaxNeedsSnacks** [comment]
I love how it's "StupidiestPlayer" as well...

**Comment by MaxNeedsSnacks** [comment]
OP unfortunately never followed up. If anyone still has problems with this please hit our support channel on discord

**Comment by tarikbir** [comment]
Hi, I'm having the same issue. My player inventory got backed up to a previous back-up but my world is still intact. Also, my player name is "undefined" now instead of what my account name is supposed to be.

I'm using GDLauncher and I don't know if there's any logs kept during runtime that I can provide.

**Comment by Frikkle** [comment]
Darkere just let us know on Discord that logging in and out of GDLauncher fixes the issue.

**Comment by Frikkle** [comment]
@tarikbir just let us know through Discord that relogging GDLauncher fixed the login issue and the playername not showing, but his inventory is still lost.

@tarikbir Could you provide any additional information that might help us drill down on the issue?

**Comment by tarikbir** [comment]
> @tarikbir Could you provide any additional information that might help us drill down on the issue?

Relogging with GDLauncher fixes the name issue. Inventory is still lost because undefined character inventories doesn't get saved somehow.

Luckily I've had it backed-up right before I logged out so I used an NBT editor to give my items back.

Leaving the world (or something else during play-through) resets the character id to undefined so I now have to leave all my items in a chest before logging out.

**Comment by TheNew1234** [comment]
Is there no fix for this? I deleted my old world, That i grinded for hours, And now is just gone, My account is not hacked, The account works fine, And my account name wasn't changed at all, Prism Launcher tho, Lets you to change your offline user name, I probably changed it without noticing as i did some testing and i found inventory conflicts between user names.

**Comment by MommyHeather** [comment]
...why would you delete your old world rather than restoring a backup or cheating back lost items?

And yes, changing your offline mode name will effectively make you a different player.

*Playing in offline mode will also cause tons of issues. Don't do that.*

**Comment by TheNew1234** [comment]
Hi there, I'm replying from an email as i'm not signed-in in github.

The world kinda got corrupted, When i log in, It switches user names and
therefore, Replacing my inventory, It was too problematic, So i just said
good bye and deleted the world, I do not have internet all time too, So i
can't really play offline, And can i ask, Does playing offline in GregTech:
New horizons also causes issues?

**Comment by HeatherComputer** [comment]
Playing offline in modded as a whole will cause various issues sadly, because you don't have a proper GameProfile for mods to interact with.
