### ISSUE TITLE
Advanced Metallurgic Fabricator loosing power

### ISSUE THREAD

**Issue by chezpaul** [NillerMedDild/Enigmatica2Expert#1003]
**Modpack version**
1.5.8

**Can the issue be reproduced?**
Yes

**Logs**
No crash log sorry.

**Issue**
This has been going on for a while now. If I have Magnesium and salt in the input hatch and I add one carbon plate my power reserve drops to 5000 (on that machine) and it won't go back up. I need to break the power block on the machine and reset it in for it to be able to load up full power again.

This used to happen gradually, meaning, it did it if I added 6 carbon plates at once but would work fine if I input them one by one. Power would go down a bit then back up. Since 1.58 it just does it after one carbon plate.

I don't use that machine for anything else.

**Comment by NillerMedDild** [comment]
How much RF/t are you giving it?

**Comment by Tntdruid** [comment]
Do you use ender io energy conduit?

**Comment by chezpaul** [comment]
Yes, I am using ender io energy.
I'm using it's lowest tier. But when I plug it back up, power comes in instantaneously. And it used to work fine in previous version packs, until I gave it too many Carbon Plates at once. (having magnesium and salt already present in sufficient quantity)

**Comment by Krapht** [comment]
I had this problem as well (but I don't remember which modular machine) and was using mid-tier energy conduits. Single crafts worked fine, but any bulk made it break. The controller stated that it did not have enough energy and IIRC it was continuously drawing more power. Since then, I've moved to using flux points and haven't had the problem since.

Speculation:
The machine requires a certain RF/t for X ticks to make the item and if it fails to draw it starts over, thus getting stuck in this loop

**Comment by Tntdruid** [comment]
I used the mekanism nerve had problems, tested whit ender io the machines had power problems.

**Comment by NillerMedDild** [comment]
Supply it with more RF/t :)

**Comment by chezpaul** [comment]
👍🏻
