### ISSUE TITLE
ME Export bus not autocrafting

### ISSUE THREAD

**Issue by mreel** [NillerMedDild/Enigmatica2Expert#1059]
**Modpack version**
Currently using 1.59a, but I remember having the same problem in an earlier version (it fixed itself after a while)

**Can the issue be reproduced?**
Not sure, probably not. See issue description.

**Logs**
N/A

**Issue**
Sometimes the autocrafting on export busses doesn't work, when given a crafting card. It does however export the items if they are already in the network. It's happening now with TBU fuel not wanting to insert into my fission reactor (nuclearcraft). It has also happened with compressed diamonds (it think, could be one of the other compressed items) into infusing factories.

The compressed items into the infusing factories happened a while ago, definitely an other version of the pack (probably a couple of versions old), but it fixed itself after a while. it doesn't happen most of the time, I just tried exporting different items into chests which all worked, and I tried to export a different fuel into the reactor, which also worked. I tried breaking and replacing both the export bus as the fission reactor, and placing them somewhere else and trying there, a all of this failed. Exporting the TBU fuel into a chest also failed. I also tried logging out of the world and logging back in, to no avail. So it seems to be item specific.

Sorry if this seems rushed, I was testing as I was writing this, and thinking of different things to test. If you need any more information, I'm happy to help.

**Comment by MorganSimic** [comment]
I remember having problems as well with export busses randomly stopping to craft while exporting.  I tried a few things, and most of the time a block update to the exporter seemed to fix it, so i assume this is a random thing within AE. 
Your issue however seems to be very specific to TBU fuel. So first i would recommend double checking every pattern needed to make TBU to make sure your system knows how to do it. Make sure you tought it TBU and not TBU-Oxide fuel for example. And make sure every other components are also the right ones. So make sure you can craft TBU within the system without exporting it. And check the crafting tab to see if it tried to craft it but failed.

**Comment by NillerMedDild** [comment]
If the steps Morgan suggests don't help, I suggest exporting to a chest and then piping the items into the Reactor from there.

**Comment by mreel** [comment]
The autocrafting of TBU fuel works, whenever I autocraft some, it does export it into the reactor. The crafting tab shows nothing is trying to craft, so it's not the craft failing, it's just the export bus that's not starting the craft. As I said exporting into a chest also fails. I try to see if updating the block helps but I highly doubt it, as I'm pretty sure I did that while trying to fix the problem in the first place.

Not at my pc atm, so I'll report back when I've been able to test it. If it still fails, I'll just autocraft a bunch and again when the stockpile runs out. Just wanted to put this on the record in case anyone else had the problem.

Thanks.

**Comment by NillerMedDild** [comment]
Silly question, but did you remember to change the Export Bus' mode?

**Comment by MaxNeedsSnacks** [comment]
It's not just Export Buses btw, had the same problem with Interfaces set to keep things stocked for my Mekanism area. Issue was in 1.53, idk if it persists but I'd have to update my server rn to find out

**Comment by mreel** [comment]
update: The block update thing definitely doesn't work, and yes, I did change the export bus mode ;)

**Comment by NillerMedDild** [comment]
Dammit :P

**Comment by puffydrink** [comment]
Silly question, but @mreel do you have enough spare cpus for the crafting card? If all of your cpus are in use for long enough and it tries to autocraft it could be freaking out. I always try to throw a few 1k cpus in any AE system because the cards will choose the smallest cpu that'll work or even give high-priority autocrafting its own cpus on a subnet.

**Comment by Tarod7** [comment]
I've also had this issue with crafting coal from mystical ag essence, breaking the ME cable fixed it. No idea what triggered it.

**Comment by IC-SubiX** [comment]
Silly question, but @mreel have you checked the chukborders? I have a simular issue with transfering items through a chunkborder into a Drawer. ( issure #1090 )




![2019-04-14_15 43 44](https://user-images.githubusercontent.com/49319663/56093699-34948a00-5ecc-11e9-8230-459c6bac3958.png)

**Comment by StefanTT** [comment]
I think I encountered the same problem, maybe this can help in the investigation:

In my case it's the Mekanism PRC - pressurised reaction chamber. It does not accept the bio fuel that it gets via AE2 export bus. It worked in 1.60 and does not work in 1.62 since the update. I did not change the machine since, it was at the spot since before 1.59 at least. Everything double checked and configured correctly. Breaking and replacing the PRC and the export bus does not help. Having bio fuel pre-crafted in the AE2 storage does not help. Export bus and PRC are in the same chunk.

As a workaround I have put an EnderIO buffer on top of the machine and export into the buffer. This works. The buffer then pushes the bio fuel into the PRC.

A quick check with a Mekanism infuser - another machine that accepts bio fuel: the infuser can get the bio fuel via an exporter. Hmm ... maybe it's a different bug but it sounds so similar.
