### ISSUE TITLE
Space the absence of mobs

### ISSUE THREAD

**Issue by Tomatoh** [NillerMedDild/Enigmatica2Expert#1107]
Just a suggestion

Find a way to add mobs in Space and maybe also have Advanced Rocketry maybe add Bosses in space as it is a little boring. Liked the Galacticraft Boss Mobs .

**Comment by MorganSimic** [comment]
There was a lot of effort to actually remove Mobs from certain planets since they die to the lack of oxygen and can contribute to a lot of server lag. And bosses on planets isn't really a good idea imho since it really doesn't fit the scope of the pack. Advanced Rocketry is mostly a means of gating and getting higher tier resources and exploration, not about combat. But there are some hostile plantes wich can inhabit mobs. So not all planets lack mobs. On the otherhand it kinda ruins the immersion of space having mobs on planets without atmosphere.

**Comment by NillerMedDild** [comment]
I agree with Morgan completely, thank you for the suggestion though.
