### ISSUE TITLE
[Suggestion] Add Wireless redstone mod

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1117]
Hey it would be nice if you could add the wireless redstone mod since i couldnt find any good way to send redstone signals over dimensions

https://minecraft.curseforge.com/projects/wireless-redstone-cbe

**Comment by MorganSimic** [comment]
There are plenty of way to wirelessly transmit Redstone in any range. Cyclic, Random Things and maybe some other add wireless redstone. For interdimensional redstone transfer there are the RF Tools Redstone Transmitter and Reciever. So this mod is not going to be added with 99% certainty, because it is mostly redundant and would add just more clutter for the most part. If you are playing singleplayer, feel free to add it yourself, it should be mostly safe to add without anything breaking by the looks of it.

**Comment by MorganSimic** [comment]
I won't close this issue just add a preliminary rejection marken, because ultimately it is for Niller to decide those things. This is only my initial review and opinion on this matter.

**Comment by niklas2233** [comment]
sound resonable now that you mention all the option i was just stupid and didnt know all thoes things

**Comment by NillerMedDild** [comment]
I agree Morgan, thank you :)
