### ISSUE TITLE
[Suggestion] Add Millenaire mod to the pack

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1118]
Hey it would be cool if you added millenaire to the modpack since it adds a lot to the villager feeling and its fun to play with

https://minecraft.curseforge.com/projects/millenaire

**Comment by MorganSimic** [comment]
Millenair doesn't fit this modpack at all. And it would be breaking apart on all fronts and is really hard to implement in a pack like this, since you really need to build around it. That is a neat tought, but will not be possible sadly. I liked Millenair back in the day. Thanks for the suggestion though.
