### ISSUE TITLE
Any XU2 recipe that requires xp doesn't show the crafting table recipe on JEI

### ISSUE THREAD

**Issue by Flamebom** [NillerMedDild/Enigmatica2Expert#1157]
**Modpack version**
1.6.2

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
XU2 items that require xp (Magical Wood, Golden Lasso and probably Magical apple) don't have their JEI crafting recipe show up.

**Comment by Flamebom** [comment]
nvm just corrupted download lol

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
I crafted one last night and I was pretty sure I did it from JEI. Just checked and for me the recipe shows. Version 1.62 stock.

**Comment by Frikkle** [comment]
@Flamebom You mentioned that after re-logging in it persists; I noticed in some other cases that in the client boot process there's a small change that items don't get properly registered (or the client crashes due to some recipe conflict, or some other mysterious reason).

Did you try restarting the client?

**Comment by stefancdr** [comment]
Can confirm I have the same issue. I had a suspicion what might be causing it, so I tried the following:

1. Tried crafting the item using the recipe (Frikkle told me what the recipe is) whilst having 0 xp. This did not work, the recipe did not show up and I could not craft the item (expected behaviour).
2. Gave myself 8 levels of XP using my XP charm and tried crafting the item. This worked as expected. Still could not see the recipe in JEI.
3. Gave myself 10+ levels of XP and restarted my client.
4. Recipe still does not work.

~~So my idea of what might be causing it is this: when you don't have enough XP to craft the item, the recipe is disabled by XU2. Since this is the case while starting/logging in, the recipe is (permanently) disabled in JEI (which should not happen) and/or it is not even registered as a valid recipe. This is probably a bug in XU2, but it might also be a bug in JEI causing it to permanently disable recipes instead of temporarily disabling them.~~

Above was my idea, unfortunately, did not fix it :-(.

**Comment by Flamebom** [comment]
@Frikkle  yeah even after relogging I can't see the recipe

**Comment by Frikkle** [comment]
Found [this](https://github.com/rwtema/Extra-Utilities-2-Source/issues/310) issue in the Extra Utils issue tracker; could be this.

**Comment by NillerMedDild** [comment]
It's not, none of those items exist in Extra Utilities for 1.12.2

**Comment by Frikkle** [comment]
Not sure if this is related, but while discussing other things today in the office I found out that at home my JEI does not show the recipe(s) for Liquifacted Coal created in the vanilla Furnace by smelting (char)coal. See [screenshot](https://imgur.com/a/S9rdAnk).

My pc in the office running the same version (1.62 stock) does consistently show the recipe while my pc at home consistently doesn't. So the scope of this might be broader.

Additionally, @stefancdr has the exact same hardware setup as I do at home and for him the Golden Lasso structurally does not show.

**Comment by stefancdr** [comment]
Just noticed the 'Magical Wood' recipe is also broken for me (not sure since when, I know it worked on our previous custom modpack). The only recipe I have available in JEI is the enchanter recipe, not the regular 'bookshelf + gold ingot + 4 XP' recipe. See screenshot:
![recipe_jei_broken](https://user-images.githubusercontent.com/4948594/57039005-ba9a2a00-6c5b-11e9-856a-d51b9cf352e4.png)

(Note: at the time of the screenshot I no longer had enough XP to craft the item, but I did succesfully craft the item 3x already, so the recipe itself does work...)

**Comment by Flamebom** [comment]
Maybe it's an issue for any recipe that requires xp?

**Comment by Flamebom** [comment]
do magical apples work?

**Comment by Frikkle** [comment]
@stefancdr could you check this tonight?

If this is the case, my missing Liquifacted Coal recipe would be another -unrelated- issue.

**Comment by stefancdr** [comment]
> do magical apples work?

Yes, they do. Unfortunately, I'm on 1.63a now which seems to work. Magical apples, magical wood and even the golden lasso work...

**Comment by Flamebom** [comment]
I mean like do the recpies show in JEI. the craft ones

**Comment by stefancdr** [comment]
Sorry for the confusion. Yes, all the recipes in JEI work for me in 1.63a, including the ones that did not for me in 1.62.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
