### ISSUE TITLE
Self disassembling ME Crafting core  

### ISSUE THREAD

**Issue by cbrueg** [NillerMedDild/Enigmatica2Expert#1199]
**Modpack version**
1.58

**Can the issue be reproduced?**
unknown
 ( Happend more than one time on  the same Server )
**Logs**
No log file cause no crash
![2019-05-20_14 17 54](https://user-images.githubusercontent.com/43262278/58021058-37f1e580-7b0a-11e9-9b76-bbcb85240f90.png)

**Issue**

Despotning blocks from mutible mutiblocks of AE2 crafting CPU's 

I've discovered a Problem with AE2 Crafting CPU from time to time the Multi block disassembles itself (explodes).
I've builded an Multi Block in following format 

cc|cc|cs|cs
cc|cc|cs|cs   cc= Crafting Co Processing Unit
cc|cc|cs|cs   cs= 64k Crafting Storage
c|cs|cs

it has an depth of 8 ( 8 Layers of this pattern )

in this Format i'd build 16 Crafting Cpu's attached  to an me smartcable wich  ended in an "Wireless Connector" wich is connected to my ME system.

I'm not sure whats triggering this Problem but it is very annoying

**Comment by NillerMedDild** [comment]
They really shouldn't be exploding, could the issue be stray creepers, or maybe a prank? 
If not, try updating :)

**Comment by MaienM** [comment]
I've had the same happen back on 1.58. There definitely were no creepers (the entire area was within the range of a peaceful candle), and no pranks (no one was playing on the server other than me).

I had placed most of the blocks using a builder's wand, and I suspected that this may have caused the problem somehow. I re-placed the blocks that broke manually, and after doing so a few times (for different blocks) the problem stopped. It have avoided using tools when placing AE2 blocks since, and I have not had the problem reoccur (but I have also not built any more CPUs since).
