### ISSUE TITLE
ME Capability Adapter AE2 cable disconects on server restart

### ISSUE THREAD

**Issue by muniategui** [NillerMedDild/Enigmatica2Expert#1203]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
No crashlog

**Issue**
When server restarts ME Capability Adapter are disconected from ae2 smart cables (did not try dense oone since adapter only suports up to 8 chanels). In order to reconect the cable you have to put a cable adjeccent to any free face of the adapter and the ae2 cables are connected properly, however even that happens they still not work.
The solution i found is you have to break and put again the adapter which is anoying after each server restart.

**Reproduce**
Create 2 compact machine and 1 tunnels (CM).
Put one of them in the overwlord.
Enter the machine and put the other CM and the Adapter adjecent to it.
Enter the nested CM and put the tunnel (acordingly to the face of the cm outside which has the adapter adjecent).
Put the other adapter adjecent to the tunnel. 
Connect any ae2 device to it using a wire.
Exit the CM.
Connect the adapter otuside to a controller or anything to check the conexion using a ae2 cable.
Restart and check the ae2 system wires adjecent to the adapters.

**Comment by NillerMedDild** [comment]
Please update and see if the issue persists.

**Comment by muniategui** [comment]
Unfortunately it persists on 1.64d

**Comment by NillerMedDild** [comment]
Alright, damn. I'll investigate.

**Comment by NillerMedDild** [comment]
Ah, known issue ><
https://github.com/ruifung/MECapabilityAdapter/issues/2

**Comment by muniategui** [comment]
Its extrange that if I broke the cable which goes from ar2 controller to ae2 pattern terminal and put it again the network reconnects even not modifing anything nor breaking the adapters

**Comment by PizzaAddict** [comment]
WORKAROUND: attach something which emits redstone signal(like RFtools Timer) to the adapter. this solves the problem.

**Comment by Frikkle** [comment]
I haven't seen this issue before whilst playing the pack and I'm doing almost everything in compact machines.

Are they in unloaded chunks?

**Comment by PizzaAddict** [comment]
+ I recommend removing the capavility adapter from mod list. It's dead mod.update stopped 2 years ago. The author seems not gonna coming back

And has A serious bug. Sometimes chunkloading state of Me network in compact machine fluctuates, therefore when I check the network with networking tool I can see blocks( interfaces...storage buses.etc) disappearing and re-appearing in real time. This bug is another bug to this(#1203) bug.

P.S:

building Me networks inside compact machines is generally a bad Idea. I've found at least three bugs on compact machines and capability adapter. I had to move my whole ME system to overworld because of them.
And the bug #1333 happend, making me groggy.

**Comment by NillerMedDild** [comment]
I am very tempted to remove it, but I fear it would ruin existing builds.

**Comment by Frikkle** [comment]
Removing ME Capability Adapters would ruin all of my server's players' builds actually. So far I haven't encountered issues specifically with Capability Adapters and ME Networks (which doesn't mean they aren't there).

I ran into a lot of other issues with Compact Machines though. Which is a whole different matter.

Instead of removing it I would opt for either adding a tooltip to the item discouraging people to use it. Or add it as text to the AE2 quest.
