### ISSUE TITLE
JavaVersionOrPathError

### ISSUE THREAD

**Issue by Vissse** [NillerMedDild/Enigmatica2Expert#1228]
When i want to start "serverstart.bat" it told me this: 

ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java.com/en/download/manual.jsp

**** ERROR ****
There was an Error, Code: ""JavaVersionOrPathError""

what to do ?

**Comment by Vissse** [comment]
I have installed the latest version of java

**Comment by NillerMedDild** [comment]
Do you have Java 9 or 10 on the PC? The serverstart script requires that you only have Java 8.

**Comment by Vissse** [comment]
oh, i just fixed that, i was searching in my pc for java files, and i found something like "java update" and it fixed that

**Comment by Caluminus** [comment]
I fixed the issue without removing any newer installations of Java by adding the following line to the ServerStart.bat script. It might not tweaking, depending on where any other versions of Java are installed.

set PATH=%PATH:C:\Program Files\Java\jdk-12\bin;=%

Since for me, JDK 12 is the only other version of Java installed, this temporarily removes it from the system path, forcing the server to run using Java 1.8. It shouldn't affect any other programs and you can keep adding these for each extra version of Java installed, as it will only make the server ignore them, not any other programs.
