### ISSUE TITLE
Item disappear with extended crafting interface and unpacker

### ISSUE THREAD

**Issue by muniategui** [NillerMedDild/Enigmatica2Expert#1245]
**Modpack version**
1.64

**Can the issue be reproduced?**
Yes

**Issue**
You put a extended crafting table (tried with the ultimate) and an automation interface over it. You fix the reciepe, in my case ultimate ingot. To automatize it you put an unpacker over the interface and you configure the interface to insert from up and extract to up. After that you request one ultimate ingot  craft in ur ae2 system, the ingot is created exported to the interface and the interface export its to the unpacker resultin in the disappearance of the ingot.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by stefancdr** [comment]
I've managed (after several attempts) to get a packing and unpacking setup working, but I always use buffer chests as an intermediary to store the input, before (indeed) sending the finished item to an interface. Note that, for packaging/unpacking to work, you need a packager and unpackager somewhere on the network **with the same recipe configured**, otherwise your item will be stuck in limbo in the intermediate package form. Have you tried a standalone setup, where the item is exported from the interface to, for instance, a chest (not connected to anything else) to verify that the problem isn't somewhere in your AE2 system?

To explain a possible AE2 system issue: if the item cannot be stored in your AE2 system for some reason, it could result in the item being dumped in an overflow chest somewhere. The contents of the overflow chests aren't always visible to the system I've found.

**Comment by Frikkle** [comment]
> Have you tried a standalone setup, where the item is exported from the interface to, for instance, a chest (not connected to anything else) to verify that the problem isn't somewhere in your AE2 system?

@muniategui Have you tried Stefancdr's suggestion above?
@stefancdr Have you been able to reproduce the issue mentioned by Muniategui? (so I can label the issue appropriately)

**Comment by stefancdr** [comment]
> > Have you tried a standalone setup, where the item is exported from the interface to, for instance, a chest (not connected to anything else) to verify that the problem isn't somewhere in your AE2 system?
> 
> @muniategui Have you tried Stefancdr's suggestion above?
> @stefancdr Have you been able to reproduce the issue mentioned by Muniategui? (so I can label the issue appropriately)

No, I haven't, because @muniategui does not describe having a packager in his network, so it would not result in a working setup :-).

**Comment by phlaxyr** [comment]
Oh! A tangentally related bug that I've found is that sometimes, with PackagedAuto, a recipe is stuck in "limbo", and can't be seen from my Wireless Crafting Terminal's Crafting Status. The ingredients for the recipe are stashed in the crafting cpus, but the recipe does not advance. You have to manually go up to the physical crafting cpu to cancel the operation, as the operation AFAIK doesn't appear anywhere else. This might be the case for what's happening here.
