### ISSUE TITLE
Server not responding and players timing out

### ISSUE THREAD

**Issue by Pabsb** [NillerMedDild/Enigmatica2Expert#1256]
**Modpack version**
Input version here Expert 1.62

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable
N/A
**Issue**
Input short description of the issue here
Server has been not responding when players go to a certain players base in the map. Players time out of just lag for minutes at a time until teleported / left the area.

If this is a feature request, feel free to delete the template.

**Comment by Frikkle** [comment]
This can have several causes, but what I've seen the most is that there's something horribly wrong with that player's setup, causing lots of server lag (which you would probably see on the server logs) or FPS lag in the client (which your description sounds like to me).

This could happen for instance when you have Auto Sieves that cannot lose their items into inventories anymore and will overflow by spilling their items all over the floor. By default in this pack the items don't despawn, causing an incredible strain on any client coming near it.

**Comment by Pabsb** [comment]
That solved all the issues! Thank you very much. Is there a way to change the Sieves settings?

**Comment by Frikkle** [comment]
Unfortunately not as far as I know. If you store stuff in drawers, add one void upgrade per drawer. If you route with enderIO you can use prioritized routing to a trash can. With itemducts I heard people say something about a void pipe. So there's many options.

You could even make a separate item collector that picks up all the stuff from the ground in the area and then voids it all. You might want to add filtering to it though. Otherwise stuff you accidentally drop is voided as well.
