### ISSUE TITLE
Mekanism Induction power structure broken / bugged

### ISSUE THREAD

**Issue by Pabsb** [NillerMedDild/Enigmatica2Expert#1257]
**Modpack version**
Input version here
Engimatica 2 Expert 1.64d

**Can the issue be reproduced?**
unknown

**Logs**
N/A

**Issue**
When updating from 1.62 expert to 1.64d I noticed that my advanced power cells are still outputting 1 million RF a tick but my Induction power set up no longer takes in 13 Mil rf a tick from my 13 advanced power cells feeding it. Instead it only takes in 1 Mil. I tried using several ports, and just Cryo-Stabilized fluxduct. Only 1 million input.

**Comment by Frikkle** [comment]
Yesterday @stefancdr built an induction matrix with a constant output of 3.9M RF output using 1.64d. So I know it can work.

Mekanism structures and blocks sometimes get bugged. It can help to reconstruct the multiblock to get it to work.

**Comment by stefancdr** [comment]
I am StefanCDR and I confirm this message.

More details: 200ish GRF capacity, 13.1 MRF output max. Quantum entangloporters to transport energy from and to the battery. Roughly 3.9M RF output was reached by connecting a Matter Fabricator from IC2 directly to a Quantum entangloporter.
________________________________

**Comment by NillerMedDild** [comment]
Do you have energy cables from all the Powercells into the Induction Matrix, or are they wordlessly connected and placed several places?

**Comment by Pabsb** [comment]
> Yesterday @stefancdr built an induction matrix with a constant output of 3.9M RF output using 1.64d. So I know it can work.
> 
> Mekanism structures and blocks sometimes get bugged. It can help to reconstruct the multiblock to get it to work.

Issue is input of power into the induction matrix not output



> Do you have energy cables from all the Powercells into the Induction Matrix, or are they wordlessly connected and placed several places?

I have all 13 advanced power cells connected to 3 Cryo-Stabilized fluxducts that go into one port shown here: https://gyazo.com/e3a8ac317f4dc27b96f4dbd48890c845

**Comment by NillerMedDild** [comment]
Thanks for the screenshot, that helps. So it's most likely the output of the Powercells that's messed up, can you guys confirm this?

**Comment by Frikkle** [comment]
I'm out for the night and can check this on Sunday at the earliest.

@pabsb what happens if you replicate this in a creative single player world? Does the same issue occur there?

Additionally, are you running E2E stock? And did you rebuild the multiblock structure as suggested?

**Comment by Pabsb** [comment]
> I'm out for the night and can check this on Sunday at the earliest.
> 
> @Pabsb what happens if you replicate this in a creative single player world? Does the same issue occur there?
> 
> Additionally, are you running E2E stock? And did you rebuild the multiblock structure as suggested?

I rebuilt the structure twice to try and fix it. I am not sure what you mean by E2E stock.

**Comment by Frikkle** [comment]
The so-called stock version, E2E "as it ships" without changes to the mods and configs.

Could you try and reproduce the issue in a new (creative) single player world as well? That would be my first shot in debugging this.

**Comment by Pabsb** [comment]
I only did changes to a few mod configs: FTB utilities, Cofh machine custom augment scaling changed server side. As to trying it in a single player world its still the same result

**Comment by stefancdr** [comment]
I cannot reproduce this behaviour in creative SP.

I setup a simple induction matrix with 1x ultimate provider and 1x ultimate storage cell, 1x input, 1x output (output was unused for this test).

Input was provided to the one input port using 3 cryo-stabilized fluxducts and 3 advanced power cells. I set all power cells to 'all output' and then saw (briefly) 3 M RF/t flow into the matrix (as expected). Afterwards, I changed the modes of the sides not facing the fluxduct to accept power and recharged them using creative power cells, then the power input stabilized on 3 MRF/t.

I will now attempt to reproduce it in SMP, but you'll have to wait a while because I don't have any of these things yet :-).

**Comment by stefancdr** [comment]
I tested it in SMP as well, still cannot reproduce your results.

[Here](https://imgur.com/F5bVWAd) is the link to the second image.

Mekanism Induction Matrix fed by 4x Advanced Powercells (which are in turn fed by Quantum Entangloporters, which are fed by the Mekanism Induction Matrix). So I've created a sort of Inception of Quantum Entangloporters, which I'm pleased to say works just fine.

**Comment by Pabsb** [comment]
> I tested it in SMP as well, still cannot reproduce your results.
> 
> [Here](https://imgur.com/F5bVWAd) is the link to the second image.
> 
> Mekanism Induction Matrix fed by 4x Advanced Powercells (which are in turn fed by Quantum Entangloporters, which are fed by the Mekanism Induction Matrix). So I've created a sort of Inception of Quantum Entangloporters, which I'm pleased to say works just fine.
> 
> Edit: I'm sorry to say I can't exactly reproduce your setup since I have not unlocked Thermal stuff yet.

You are on the 1.64d Pack version correct?

**Comment by Pabsb** [comment]
Me trying it in single player shown here: https://gyazo.com/10555f5877fe7ff2307965a662d88f71, https://gyazo.com/2154d1f40091a7398137920d10a4e7fb has the same result as in my server

**Comment by stefancdr** [comment]
What is feeding power into the advanced powercells? As, when I tested it, they drain in 2 seconds (since they only store 40 MRF, and drain 1 MRF/t, and 20 ticks is 1 second (IIRC)). It's very hard to show that it works. And yes, I am on 1.64d.

**Comment by Pabsb** [comment]
> What is feeding power into the advanced powercells? As, when I tested it, they drain in 2 seconds (since they only store 40 MRF, and drain 1 MRF/t, and 20 ticks is 1 second (IIRC)). It's very hard to show that it works. And yes, I am on 1.64d.

In the 2 screen shots I provided above you can see a Fusion Reactor

**Comment by stefancdr** [comment]
Yes, but it is not connected to the cells in any way as far as I can tell? I see no conduit or wireless connection between it and the cells?

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by Pabsb** [comment]
> Yes, but it is not connected to the cells in any way as far as I can tell? I see no conduit or wireless connection between it and the cells? Edit: removed stupid mobile stuff :-).

Advanced power cell on the other side of the reactor is what feeds induction matrix

**Comment by Frikkle** [comment]
But the Advanced Power Cell has a 1M RF/t transfer rate, right? So, this means that the "entry point" to your power cell buffer is capped on a 1M RF/tinput rate; causing the power cells to gain energy with that amount. You can extract with 13M RF/t, but your buffer can only charge with 1 RF/t.

You can increase this probably by adding some more cry-stabilized fluxduct directly against your reactor and feeding into a higher of advanced power cells. This way you input rate (and thus the setup's throughput) will be higher overall.

The mentioned 13M RF/t probably was because your buffer was initially full before connecting it to your Induction Matrix; hence the first period of time it would have emptied your buffer out at max output transfer rate. Once the buffer got emptied out, you are capped by the input rate.

If you are really really sure that you had a stable 13M input through that one cell; then this might have been a bug with RFTools which has been fixed, ór a bug with RFTools that has been introduced. In either of those case it probably would need to be reported over there.

But from what I see and you guys describe and tested, this behaviour really makes sense to me.

**Comment by Frikkle** [comment]
@Pabsb just let me know via the Discord #support channel that he switched to using Quantum Entangloporters.

Since we cannot reproduce the issue and I think it's functioning as it should I'll mark the issue closed. If someone has more information on this we can always reopen it.
