### ISSUE TITLE
Mod request: FlightBoost

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#1281]
[FlightBoost](https://www.curseforge.com/minecraft/mc-mods/flightboost) adds items that boost your elytra, like fireworks do. One that has durability, and one that uses FE. They can also be enchanted to use less durability/energy, give a better boost, and have a lower cooldown. Great for exploration or mobility!

**Comment by NillerMedDild** [comment]
I'll think about it :)

**Comment by MorganSimic** [comment]
I feel something like that isn't necessary. There are so many mobility options available already between Slime Sling, Player Launcher, Glider, Staff of Travelling, Flight Charm and many more. So i feel something that boost the elytra isn't needed because nobody uses the Elytra. Especially because the Open Blocks Glider does exist. And considering the state of the pack i would avoid adding anything that isn't absolutely paramount for improved gameplay experience. Just my two cents on the topic.

**Comment by NillerMedDild** [comment]
I agree with Morgan, sorry :)
