### ISSUE TITLE
Crash on Quest Claim

### ISSUE THREAD

**Issue by rjzvara** [NillerMedDild/Enigmatica2Expert#1319]
**Modpack version**
1.67

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/HTDbAudD

**Issue**
tried to claim the starting reward: the backpack parts and leather armor

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

If that doesn't fix the issue, please let me know :)
