### ISSUE TITLE
Iron frame autocrafting attempts to use non-existing iron rod

### ISSUE THREAD

**Issue by stragulus** [NillerMedDild/Enigmatica2Expert#1325]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
Reproduce steps:
- Open ME crafting terminal
- Select 'crafting pattern'
- Put in blank crafting pattern
- Search for 'iron frame'
- Click 'plus' icon to to populate the crafting pattern
- Click 'encode pattern' to generate pattern

Generated pattern will refer to Iron Rod from Vulpes library, which is not craftable

**Comment by Frikkle** [comment]
There are more recipes for which a similar thing happens. It has to do with the fact that the recipe is set to use "any: rodIron" so it will auto-fill using the first registered rodIron item type it finds. You can craft a "regular" iron rod and place that in the recipe yourself to make the auto-crafting work.

Additionally I think the Iron Rod from Vulpes can actually be made using the Advanced Rocketry Lathe machine. But I'm not sure and not near a computer to check.

Leaving this open for Niller to close it appropriate but I don't think there's an issue here.

**Comment by PizzaAddict** [comment]
@frikkle lathe produces Immersive engineering rods same for steel, and aluminium

**Comment by NillerMedDild** [comment]
This is indeed a limitation of making patterns without having the materials present in your system.

**Comment by Frikkle** [comment]
@pizzaaddict thanks for adding this. I wasn't sure on the exact item production and couldn't check. One of the cons of being on holiday in the middle of the woods.

**Comment by FishOutOfH20** [comment]
> 
> 
> This is indeed a limitation of making patterns without having the materials present in your system.

Hi.  Could you clarify this answer please?  I keep encountering this issue and have to go back and remake the pattern.

I just made the pattern for the lens from advanced rocketry.  When I went to craft it, it asked for a rod from Vulpes, so I had to go change the recipe to use the IE iron rod.  When I made the pattern, I had hundreds of iron rods in my AE2 system.

It just seems frustrating to constantly have to go back and change patterns because I didn't notice it was using the Vulpes version.  Considering there are 3 Vulpes rods in the game, it gets a bit confusing.

**Comment by NillerMedDild** [comment]
Hmm that doesn't sound good, I've opened a new issue to investigate that issue: #1702
