### ISSUE TITLE
creating terrasteel causes MASIVE lag spike to computer. cannot enter world anymore.

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2Expert#138]
#### Issue Description
After making the terra plate I set up the multiblock and the started the craft. once making it the computer starting locking up. giving me around 1 frame per minute. 

I have a mod installed which lets you keep playing even though a game crashes (and gives you the report with it). its called VanillaFix.  it said that there was apparently a spam of errors from botania as I tried to create the terrasteel.

#### Modpack version (Do not use "latest")
1.30
#### Crash Report

When this occured. it created 50+ crash reports. I think this might be created from vanilla fix. this is the latest one.

https://pastebin.com/UVkcpvw3

**Comment by NillerMedDild** [comment]
Can you reproduce it without VanillaFix?

**Comment by DragonmasterDJ** [comment]
@NillerMedDild sorry for the wait. 
I removed vanila fix and it fixed the problem.
How come the mod which is supposed to help you out, make it worse?

**Comment by NillerMedDild** [comment]
I don't know Vanillafix well enough to answer that.

**Comment by Discomanco** [comment]
"Yes, there should be. The error is caused by an uncaught exception in a scheduled task (Minecraft.getMinecraft().addScheduledTask, Minecraft.getIntegratedServer().addScheduledTask). All that VanillaFix does is inform the player that something went wrong and make a report which helps them and the mod author solve their problems."
From the other issue
