### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by SamuelBucher** [NillerMedDild/Enigmatica2Expert#1381]
**Modpack version**
1.70

**Issue**
Whenever I try to open my inventory my game crashes. It started when I tried to view the recipe of the thermoelectric generator from immersive engineering through JEI. Game crashed. Then I tried to do the same through the Quest bock. Crash.  After this, just opening my inventory causes a crash. Everything is perfectly fine in my other worlds.

**Logs**
https://pastebin.com/ctHZ62wR

**Comment by NillerMedDild** [comment]
We need the full crash report to help you properly.

**Comment by SamuelBucher** [comment]
Should be good now.

**Comment by NillerMedDild** [comment]
Thanks.
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
