### ISSUE TITLE
Crashes after 2 hours

### ISSUE THREAD

**Issue by Cortex788** [NillerMedDild/Enigmatica2Expert#1392]
**Modpack version**
1.69
**Issue**
The modpack crashes after 2 hours

**Comment by NillerMedDild** [comment]
Please provide your crash report.

**Comment by Cortex788** [comment]
After 2 hours the game is freezing for 10 minutes and i cant do nothing.Then the game crashes
![Заснемане](https://user-images.githubusercontent.com/57009314/67636872-a3bc5380-f8dd-11e9-91fd-706273404819.PNG)

**Comment by NillerMedDild** [comment]
Please provide your crash report. It's in the crash-reports folder in your Minecraft instance.

**Comment by Cortex788** [comment]
[crash-2019-10-21_19.01.06-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3776151/crash-2019-10-21_19.01.06-client.txt)

**Comment by NillerMedDild** [comment]
Alright you have two issues:

1) You do not have enough RAM allocated. You need a minimum of 6GB allocated to run Enigmatica 2: Expert. This is done through Twitch's Minecraft settings.

2) You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by Cortex788** [comment]
I have 8 gb of ram but it crashes.I think it's because of the java version

**Comment by NillerMedDild** [comment]
Your PC may have 8GB RAM, but you need to allocate it to Minecraft.
