### ISSUE TITLE
Ore Excavation / Storage Drawers

### ISSUE THREAD

**Issue by sarcastic6** [NillerMedDild/Enigmatica2Expert#1512]
**Modpack version**
1.76a

**Issue**
Is it possible to blacklist storage drawers in the Ore Excavation config?  I just accidentally used a Tinkers Construct hatchet with ore excavation on a set of framed drawers containing a bunch of items and it gladly broke them all -- and dropped a set of empty drawers.  

**Logs**
N/A

**Comment by sarcastic6** [comment]
Hmm, this isn't what I had originally thought it was.  Sometimes when I break drawers they keep their contents and sometimes they just turn into an empty drawer and don't drop anything -- but it's not Ore Excavation, because it's happening to single ones now, too.  I'm going to close this until I can reproduce what's actually going wrong and go from there...

**Comment by Lgmrszd** [comment]
Just to clarify: after last Storage Drawers update, all drawers should have their content instead of dropping it (to prevent lag from dropped items), but framed drawers do not contain items nor drop them after breaking (this issue: https://github.com/jaquadro/StorageDrawers/issues/783). As a workaround, use tape from this mod to seal these drawers first.
