### ISSUE TITLE
Personal Nano Bot Beacon is overpowered

### ISSUE THREAD

**Issue by NovaBomber** [NillerMedDild/Enigmatica2Expert#1584]
**Modpack version**
1.77

**Issue**
The Personal Nano Bot Beacon from Environmental tech can make you invulnerable (with the exception of chaos dragon). If you get up to a tier 5 controller, it's possible to add 5 resistance modifiers and buff yourself to 100% damage reduction.

I would think capping it to resistance 4 or even 3 would nerf it enough.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll think about it :)

**Comment by NillerMedDild** [comment]
I increased energy cost of it by 4x, which is the max. I cannot limit the total amount allowed.

**Comment by bibo38** [comment]
I would suggest changing the recipe for the resistance modifiers. Otherwise this just feels like having the infinity armor from Avaritia mid game. I suggest to replace the shields in the recipe with infinity ingots or catalysts.

The (personal) nano bot beacon is already a great deal, having the ability to fly/heal/night vision/... in any dimension. Not having the protection modifiers is just a little constraint to prevent it from being op.

Furthermore there is also the option to give the player some resistance modifiers early on through the quest system (maybe for the tier 6 nano bot beacon).

**Comment by NillerMedDild** [comment]
So I went with nerfing the tier 5 / 6 controllers, as this isn't really an issue prior to tier 5 as far as I understand. Here are the recipes (in code)

```java
# Personal Nano Beacon tier 5 + 6 harder recipes, to limit access to Resistance 5 (100% damage reduction)
recipes.remove(<environmentaltech:nano_cont_personal_6>);
recipes.addShapedMirrored("enigmatica_nano_cont_personal_6", <environmentaltech:nano_cont_personal_6>, 
[[<ore:blockCosmicNeutronium>, <ore:blockDraconiumAwakened>, <ore:blockCosmicNeutronium>],
[<ore:blockAethium>, <environmentaltech:nano_cont_personal_5>, <ore:blockAethium>], 
[<environmentaltech:mica>, <environmentaltech:modifier_null>, <environmentaltech:mica>]]);

recipes.remove(<environmentaltech:nano_cont_personal_5>);
recipes.addShapedMirrored("enigmatica_nano_cont_personal_5", <environmentaltech:nano_cont_personal_5>, 
[[<ore:blockCrystaltine>, <draconicevolution:draconium_block:1>, <ore:blockCrystaltine>],
[<ore:blockIonite>, <environmentaltech:nano_cont_personal_4>, <ore:blockIonite>], 
[<environmentaltech:mica>, <environmentaltech:modifier_null>, <environmentaltech:mica>]]);
```
