### ISSUE TITLE
Access Violation Exception crash on modpack start

### ISSUE THREAD

**Issue by iComputerfreak** [NillerMedDild/Enigmatica2Expert#1588]
**Modpack version**
1.77

**Issue**
Sometimes (about 50% of the starts) the game crashes during launch resulting in an Access Violation Exception.

This has been already reported for version 1.62 in #1154, but I was having it in 1.77 too.
You stated the problem as outdated java version (he was using Java 1.8, as am I).
What java version would you recommend for Minecraft? Last time I tried using Java 10 not even Vanilla Minecraft would start.

**Fix**
For everyone else still having the issue, it can be fixed by disabling the Deduplicator of the FoamFix mod. Just set these three settings in **foamfix.cfg** to false:
```
B:clearDuplicateModelRegistry=false
B:deduplicateModelBakers=false
B:deduplicateModels=false
```

This may be worth putting in the next update, since I am guessing, that there are still many people that use Java 1.8 for Minecraft.

**Comment by NillerMedDild** [comment]
The issue is not whether to use Java 7, 8, 9 etc - The issue is using the ancient version of Java 8 that both Minecraft and Twitch ship with Minecraft.

The correct java to use is the latest Java 8 64-bit, found here: https://java.com/en/download/manual.jsp
It's called `Windows Offline (64bit)` on the website.

I would like your crash report please :)

**Comment by iComputerfreak** [comment]
Here is the crash log: (https://pastebin.com/GxitcY0T)

As I said, I already found a fix/workaround that seems to work (disabling the deduplicator).
I just opened this issue so you and other people know about it and you can consider changing the config in the next version.

Reading the crash log I see, that I too seem to use an outdated build... (1.8.0.51), which is strange, since my active java version is 1.8.0.241
```
> java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Comment by NillerMedDild** [comment]
I won't change the config, as using the outdated Java version will cause a host of other issues, including tons of different in-game crashes, and the configs improve performance.

Your issue is caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
