### ISSUE TITLE
looking at immersive water wheel resipe

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica2Expert#1598]
**Modpack version**
1.77

**Issue**
looking at immersive water wheel in jei will crash you out to launcher

**Logs**
happened to team mate will have him post crash logs but ya should be easy to test

**Comment by NillerMedDild** [comment]
Interesting, looking forward to seeing that crash report :P

**Comment by noa12390** [comment]
seems to be a conflict with current version of optifine

**Comment by noa12390** [comment]
[crash-2020-04-01_15.33.25-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4417666/crash-2020-04-01_15.33.25-client.txt)

**Comment by NillerMedDild** [comment]
That it does. His Java is also outdated. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
