### ISSUE TITLE
Inconsistencies related to processing armor and weapons dropped by mobs

### ISSUE THREAD

**Issue by SReject** [NillerMedDild/Enigmatica2Expert#1634]
**Modpack version**
Enigmatica 2 Expert v1.83

**Issue**
There are a few inconsistencies when it comes to armor and weapons dropped by mobs:

- All Twilight Forest armor sets can be deconstructed into ingots via a crafting table when fully repaired. This seems odd in the scope of the pack especially after arc-furnace recipes were added for the sets
- Flux-Infused armor from Redstone Arsenal do not have an arc-furnace recipes even though  the tools from the mod do.
- Psimetal tools and armor do not have a deconstruction recipe, in either the arc-furnace or crafting table - noa12390

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by noa12390** [comment]
same applies to psi armor

**Comment by SReject** [comment]
To clarify, Psi armor doesn't have an arc-furnace recipe to turn the armor into ingots.

As an aside, it doesn't have a crafting bench recipe either.

**Comment by NillerMedDild** [comment]
TF armors can be recycled easier in an effort to limit the frustration some may feel with going through the Twilight Forest for armors.

Flux-Infused Armor is made out of Fluxed Armor Plating, whereas the tools are made of Fluxed Electrum Ingots, that's why one can be recycled and the other cannot. Making it possible to recycle them for Fluxed Armor Plating seems a bit silly, is it can only be used to make new armor.

I agree that it's inconsistents, but it's intentional *for the most part* :)

Thanks for the report.
