### ISSUE TITLE
Basic Machine Casing Cannot Be Replicated With UU Matter

### ISSUE THREAD

**Issue by ForeignPie** [NillerMedDild/Enigmatica2Expert#1705]
**Modpack version**
1.80

**Issue**
Despite Advanced Machine Casing being able to be replicated, Basic Machine Casing cannot be scanned and replicated. This seems rather bizarre so I assume it's an oversight.

**Comment by NillerMedDild** [comment]
I honestly can't remember if that's intended, it does sound like an oversight :P

**Comment by MorganSimic** [comment]
To be honest i feel this alright as is. The basic machine casing is very easy to automate with uu-matter with very little steps involved. All the other casings make sense since they involve quite a bit microcrafting. But the basic casing is just a few steps and it's nice to have at least some machine casings that need to be automated, apart from the EIO and AR ones.

**Comment by ForeignPie** [comment]
But, near as I can tell, you can't automate basic machine casing with UU matter. Aluminum can't be scanned.

**Comment by NillerMedDild** [comment]
Why does it have to be with UU matter? :P

**Comment by ForeignPie** [comment]
Just feels like the Industrial Craft machine meant to automate creation of objects should be able to make the basic crafting components of Industrial Craft machines. Maybe that's just me.

**Comment by NillerMedDild** [comment]
That is a pretty good point.
