### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by Shrakakoom** [NillerMedDild/Enigmatica2Expert#1707]
**Modpack version**
1.80

**Issue**
Game is crashing mid-launch, at step 6/7. Java has been updated to version 8 update 251. Loading game using JAR launcher through Twitch. 

**Logs**
https://pastebin.com/u5gqcq8y
https://pastebin.com/JYSRzMP1

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

I recommend that you read this document about setting up the modpack: https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185 :)
