### ISSUE TITLE
Bright Flashing when looking at blocks in Compact Machines

### ISSUE THREAD

**Issue by DomLikesPython** [NillerMedDild/Enigmatica2Expert#1752]
**Modpack version**
1.80

**Issue**
Occasionally when inside of a Compact Machine (I've only used the maximum size), and only when looking at a block, the screen will rapidly flash, apparently alternating between the original textures, and full white or black, depending on the block.

I believe the issue is with WAILA, and possibly Optifine or VanillaFix, because the issue can be fixed by disabling WAILA when in a Compact Machine.

**Logs**
This issue doesn't crash the game, but is severe enough that it could affect people prone to light-induced seizures.

**Comment by MorganSimic** [comment]
Your description implies you are using Optifine and VanillaFix. Both are not default version of the pack. So please see if the bug occurs with these additions disabled. Otherwise you are pretty much on your own as we don't support custom modifications.
So please try without these mods and report again.

**Comment by DomLikesPython** [comment]
Sorry for the delay, but I pretty much can't play the pack without either.

**Comment by NillerMedDild** [comment]
Damn, alright :/ We'll see if we can reproduce it without then.

**Comment by eggshellsv** [comment]
I can confirm that this only happens with Optifine. It's happened to me multiple times on various packs, and normally a relog should fix it
