### ISSUE TITLE
Game Crashes When I Try to Open the Pack

### ISSUE THREAD

**Issue by keremlov** [NillerMedDild/Enigmatica2Expert#1755]
**Modpack version**
1.81a

**Issue**
Crashed when I tried to open the pack

**Logs**
https://paste.feed-the-beast.com/view/3f809868

**Comment by NillerMedDild** [comment]
I'm on mobile so the log in hard to read, but:

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
