### ISSUE TITLE
Might be bug or i am just dumb!

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1759]
**Modpack version**
1.80

**Issue**
Me interface when changed shape to flat one and renamed wont let me change shape to square one. (Didn't tried naming square one and changing to flat me interface). Ask if need more information.

**Comment by NillerMedDild** [comment]
Hm, we'll have a look :) thanks!

**Comment by Nabbieshtron** [comment]
I checked some things and made a small video didnt know where to upload so did on youtube https://youtu.be/g-DuaLPqxw0

**Comment by NillerMedDild** [comment]
Thanks! I'm fairly certain I can fix that.

**Comment by Nabbieshtron** [comment]
One more thing you cant use renamed interface in other recipes idk if thats helps.

**Comment by NillerMedDild** [comment]
I think this is a limitation of most items to be honest.

**Comment by Nabbieshtron** [comment]
Į dont know maybe i should put it in request tab but į would likę renamed objects to revert to original item name but į can just rename it

**Comment by musicsoul0142** [comment]
It would be nice to get it fixed, but I don't think this bug is serious.
You can revert the name by placing the renamed item in Anvil, leaving the name field blank and paying 1Lv. In that state, you can successfully revert to a box shape.
![fc0153e5570407430b7a7fe4ff44996b 1](https://user-images.githubusercontent.com/54382718/89372063-0cafe200-d720-11ea-8285-8e1a331deccc.gif)

**Comment by NillerMedDild** [comment]
This would take too much time to fix considering the limited pay-off, sorry :)
