### ISSUE TITLE
IC2 Quantum Suit

### ISSUE THREAD

**Issue by Lavariator** [NillerMedDild/Enigmatica2Expert#1771]
**Modpack version**
1.81a

**Issue**
Currently there is no way to deactivate the jetpack of the QuantumSuit Bodyarmor or to activate the jump boost of the QuantumSuit Boots. I think its because the Boost Key doesn't work correctly. I tried changing the keybind multiple times but this didn't made it worth either.

**Comment by NillerMedDild** [comment]
We are aware of the issue, and I highly doubt it will ever be fixed I'm afraid, since it's a bug in IC2

**Comment by Timic3** [comment]
It's not really a bug, I'd say it's just not implemented - I checked IC2 bytecode and I couldn't see it implemented anywhere. It's just always active:
```java
public boolean isJetpackActive(ItemStack stack) {
    return true;
}
```

I fixed it by changing bytecode to return false, because I already got the Angel Ring, so I don't need integrated jetpack. I would make a mod that addresses this properly, by adding a keybind and all, but I have little to no experience with Forge (I guess using reflections would work here). Too bad IC2 isn't open source tho.
