### ISSUE TITLE
Iron golem don't drop iron

### ISSUE THREAD

**Issue by set92** [NillerMedDild/Enigmatica2Expert#1809]
**Modpack version**
1.81a

**Issue**
As title says, I build an iron farm to discover that iron golems only drop poppies, and I didn't know in which file I could revert this change, and since I haven't seen any discussion or changelog with this info maybe it is a bug? If not in which file I could re-add iron as drop?

And for mekanism basic universal cable I find the recipe too weird, since it requires technology, as enderIO that I shouldn't have until too much down the line, because in the Gates quest line EnderIO is almost at the end game, and mekanism in the 2nd row. So I suppose the solution is use other mods to cover the electricity for mekanism? And is not too expensive and time consuming to build the cables from mekanism? Like too many things build from other complex items for cables, which you will need to build a lot of them.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
The Basic Universal Cable recipe is hard in an effort to make you use other cables, because they're not the greatest in terms of lag, and because they're capable of converting between FE and EU.

I'll look into the Iron Golem issue, I don't remember disabling their iron drop, but it does sound like something I would do :P

**Comment by NillerMedDild** [comment]
Yep I did remove that :)
