### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by yusuffunworld** [NillerMedDild/Enigmatica2Expert#1829]
**Modpack version**
1.81a

**Issue**
modpack crash on start up of world

**Logs**
[crash-2020-10-10_11.52.01-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/5358809/crash-2020-10-10_11.52.01-client.txt)

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

If this does not solve the issue, please make use of our Discord's support channel :)
