### ISSUE TITLE
Some way to efficiently empty the /dank/null?

### ISSUE THREAD

**Issue by mhelvens** [NillerMedDild/Enigmatica2Expert#1860]
**Modpack version**
1.82a

**Issue**
Checking the changelogs, I see the /dank/null docking station was disabled because people were abusing it for storage. Fair enough. However, I tended to use the docking station to empty the /dank/null into my storage drawers, and I don't know how to do that now except manually, stack by stack.

Is there some method I'm overlooking? If not, would you consider enabling my usecase without opening it back up to abuse? Some ideas that come to mind:

* Allow shift-right-clicking the /dank/null on a drawer controller to empty it.
* Make the docking station incompatible with the ME Storage Bus and Export Bus, but allow the Import Bus.
* Just give the docking station a more expensive crafting recipe?

**Comment by NillerMedDild** [comment]
The main reason that the Docking Station was removed was because it frequently caused massive lag and crashes on the official E2E server :/

> Allow shift-right-clicking the /dank/null on a drawer controller to empty it.
Make the docking station incompatible with the ME Storage Bus and Export Bus, but allow the Import Bus.

We don't have that kind of control I'm afraid.

Your usecase is very valid, but we have yet to come up with a reliable way of allowing it :/

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
