### ISSUE TITLE
1.34 Pam's Harvestcraft Ground Trap not working with grass blocks around it at high elevations. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [NillerMedDild/Enigmatica2Expert#200]
v.1.34

Hi there. I tried to use the ground trap up about y 205 in the Alps, and the ground trap didn't start consuming the bait. When I took it back down to y 65, it worked fine. It appears your ground trap has issues with different world heights. Would you mind looking into this please?

Even with a bunch of woven cotton inside the machine, the water filter won't accept freshwater items to make salt.

Please consider looking into these and thank you for your time.

-crossposted with Harvestcraft github

**Comment by NillerMedDild** [comment]
Since the Ground Trap is an item that traps animals (albeit non-existant ones), it makes sense that it doesn't work in heights that are mostly inaccessible. 

The Water Filter makes Fresh Water and Salt, when supplied with Woven Cotton, and a Water Source block on top of it, flowing down on all sides.
