### ISSUE TITLE
astral sorcery luminous crafting table

### ISSUE THREAD

**Issue by lp2257** [NillerMedDild/Enigmatica2Expert#238]
#### Issue Description
Astral Sorcery luminous crafting table not crafting any recipe
#### Modpack version (Do not use "latest")
Enigmatica2Expert 1.36
#### Crash Report

[pastebin/gist/etc link here]

**Comment by ZephyrWindSpirit** [comment]
Right click the table with a resonating wand. It also needs adequate starlight for recipes with the bar at the bottom.

**Comment by lp2257** [comment]
i did and i putit next to the cristal in the temple but is not working and when i put the iteam in the table the outcome dosan show In addition reinstalld the pack and tested in test world no go

**Comment by drakkensong21** [comment]
Is that the first level of the table I can't remember

**Comment by drakkensong21** [comment]
Did you use the white pettle

**Comment by lp2257** [comment]
Yes but all the recipes dont work

**Comment by NillerMedDild** [comment]
Did you craft the table yourself?

**Comment by lp2257** [comment]
yes

**Comment by NillerMedDild** [comment]
Does it have a clear view of the sky?

**Comment by LumberWizard** [comment]
"i did and i putit next to the cristal in the temple but is not working and when i put the iteam in the table the outcome dosan show In addition reinstalld the pack and tested in test world no go"

Something tells me he/she didn't.

**Comment by MadCat64** [comment]
I had the same issue.  The table looked like a luminous table but only acted like a normal crafting table.  I thought maybe it was because I made the wand using an enderpearl instead of the salis mundus but that wasn't the problem.  History - I found a temple, made the luminous crafting table and wand.  I dug a hole above the crystal to the sky and nothing.  No bar and no recipe shown.  I realized I didn't have a white petal and when I put the white petal in it worked - although that was several server and game restarts later.

I can't say what the problem was or how it was fixed. Maybe it was clicking the checkmark and turning in the first quest for the Astral Sorcery tab which has a command as a reward.  Make sure there are no blocks between the crystal and the sky and try again?

**Comment by NillerMedDild** [comment]
Completing quests does not affect progress or item availability in any way.

**Comment by leftyde** [comment]
I had the same issue, found a solution on web to use a command for the as progress tree to realize that I can use that table, after that all other tables worked fine! Just the first one had the issue. Dont know the command anymore :(

**Comment by NillerMedDild** [comment]
All the command does is run the command that is run when you craft the Luminous table.
