### ISSUE TITLE
Configure Block Breakers Correctly

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#258]
- OpenBlocks block breaker (seems fine)
- Random Things block breaker (haven't tested it)
- Arcane Bore (haven't tested it)
- RFTools builder (seems fine)
- Mekanism Digital Miner (I have not used that block once in my entire life)
- ME Annihilation Plane (seems fine)
- Integrated Tunnels World Block Importer (does not work for most blocks)
- Thaumcraft Golem with breaker arms (breaks the blocks but doesn't drop their drops)
- Astral Sorcery break lens (same as above)
- Cyclic Simple Miner (haven't tested it)
- Cyclic Controlled Miner (uses a pickaxe so it's fine, albeit super slow for some reason)
- Botania Bore Lens (does up to mining level 3)
- Mining Turtles (does not work for most blocks)
- Actually Additions auto breaker/phantom breaker/etc. (do not work)

**Comment by LumberWizard** [comment]
Might as well write everything I determined by testing as well:
OpenBlocks Block Breaker successfully mines blocks up to mining level 4, blocks of mining levels 5-14 disappear when broken by it.
Random Things Block Breaker successfully mines blocks up to mining level 4, blocks of mining levels 5-14 remain untouched by it.
The Arcane Bore takes a pickaxe and mines according to that pickaxe's level. blocks with a higher mining level than that pickaxe can mine remain untouched by it.
The RFTools builder (at least in quarry mode) mines up to mining level 12, and leaves blocks with a higher mining level unaffected.
The Mekanism Digital Miner is able to mine all blocks.
ME Annihilation Planes can mine all blocks.
Integrated Tunnels World Block Importers can mine all blocks that don't need a pickaxe (note that blocks like livingwood with a mining level of 4 can still be mined by them). Blocks they cannot mine they leave in the world.
Thaumcraft Golems with Breaker Arms can mine all blocks that don't need a pickaxe (note that blocks like livingwood with a mining level of 4 can still be mined by them). Blocks that need a pickaxe are destroyed and drop nothing.
The AS Break lens can mine all blocks that don't need a pickaxe (note that blocks like livingwood with a mining level of 4 can still be mined by it). Blocks that need a pickaxe are destroyed and drop nothing.
The Cyclic Simple Miner successfully mines blocks up to mining level 4, blocks of mining levels 5-14 remain untouched by it.
The Cyclic Controlled Miner takes a pickaxe and mines according to that pickaxe's level. blocks with a higher mining level than that pickaxe can mine remain untouched by it, and cause it to get stuck (since it mines in an area, when it gets to a block it can't mine it'll stall forever).
The Botania Bore lens successfully mines blocks up to mining level 4, blocks of mining levels 5-14 remain untouched by it.
Mining Turtles can mine all blocks that don't need a pickaxe (note that blocks like livingwood with a mining level of 4 can still be mined by them). Blocks that need a pickaxe are destroyed and drop nothing/don't go int othe turtle's inventory.
Actually Additions Breakers/Long Range Breakers/Vertical Diggers can mine all blocks that don't need a pickaxe (note that blocks like livingwood with a mining level of 4 can still be mined by them). Blocks they cannot mine they leave in the world. Phantom Breakers don't seem to be working at all in my creative test world, but I could be using them wrong.
Industrial Foregoing Block Breakers successfully mine all blocks.

**Comment by NillerMedDild** [comment]
I think I got the vast majority of them either fixed or removed, thank you for your hard work as always :)
