### ISSUE TITLE
[Request/Discussion] A middle point between Enigmatica 2 and Expert

### ISSUE THREAD

**Issue by MechanosG** [NillerMedDild/Enigmatica2Expert#329]
**Is your feature request related to a problem? Please describe.**
Basically...  Enigmatica 2 is great, but has quite a few overlapping balance/progression breaking mods.  Plustic tinker armor makes you invincible pretty early game.  The nutrition mod compounds it further after spamming one of every pam food getting you 60+ hp.  Energy generation can be super cheap with one mod, yet expensive and not as useful in another.  Environmental Tech lets you pull infinite ore out of thin air.  Etc etc, stuff you're fully aware of.

However, Enigmatica 2 Expert makes things pretty hardcore and goes beyond just balancing things out.  I can live with the expensive recipes and gating somewhat.  But no vanilla tools + plank/stick nerf + buggy veinminer that doesn't seem to want to work (grave opens my questbook and remapping the key doesn't seem to help) = I'm spending multiple days punching wood to get tinker's going, forcing me to sit through boring blocked in nights in between.  It feels far too annoying to start a new game.

**Describe the solution you'd like**
My solution/request, is a pack like Enigmatica 2 (or an optional config), that has been balanced more or less like the Expert pack, just less hardcore.  I'm looking for a kitchen sink that has balance and progression between mods, but not time wasting grinds inserted into non-important parts of the game.  To re-iterate, I'm more than willing to have to pay more expensive recipes and hop around in between mods to get things crafted.  But when even getting to the starting line becomes a grind, it's difficult for some players to keep interested.

**Additional context**
I realize this is probably too much to ask.  Making a good modpack isn't a small task.  So know that I'm realistically not expecting any kinda of response saying you'll get right on it.  I'm just merely suggesting the idea, as I've put a lot of time into Enigmatica 2 now, and I'm really impressed with it.  Easily makes my top 3.  I'm just not so impressed with how OP some stuff is, and really like the idea of more cross-mod interactions.

Thanks for reading.

**Comment by NillerMedDild** [comment]
Your hand cannot be empty if you want to use veinminer/ore excavation. Rebind the key, and hold it down whenever you want to use it.

Believe it or not, I actually have balanced energy production extensively in Enigmatica 2, some of the options are far more OP by default. I really get that you'd like an "in-between" modpack, but I'm afraid I simply don't have the time or motivation to make it. Such a project would take at the very least 6 months to finalize.

I will work towards balancing Enigmatica 3 as much as possible when the time comes however :)

**Comment by z64555** [comment]
My opinion is that kitchen sinks shouldn't try to balance mods to coop with each other, especially when there's tutorial quests in there to guide your progression in the mods individually.  The pack is so that you can experience and play with the individual mods as you like, without needing to make a pack specifically for each individual mod.

Some mods are naturally balanced versus each other and vanilla minecraft, namely Thermal Expansion (and cohorts), Forestry, and IndustrialCraft 2, whereas many others are balanced versus vanilla (such as Mekanism, Tinkers Construct), and some that throw balancing out the window (Draconic Evolution).

Trying to balance a kitchen sink pack doesn't make it a kitchen sink pack anymore, instead its a hodgepodge of different mods cobbled together and a half-hearted attempt at making an intended progression path.

A method of removing permanent "progression breaking" buffs might be beneficial for those who are interested in seeing what a mod would be like from a fresh start, but it would still be up to then over what path they take.

**Comment by NillerMedDild** [comment]
Very good point. I'll limit balancing to energy generation, very overpowered things and exploits.

**Comment by MechanosG** [comment]
> 
> 
> My opinion is that kitchen sinks shouldn't try to balance mods to coop with each other, especially when there's tutorial quests in there to guide your progression in the mods individually. The pack is so that you can experience and play with the individual mods as you like, without needing to make a pack specifically for each individual mod.
> 
> Some mods are naturally balanced versus each other and vanilla minecraft, namely Thermal Expansion (and cohorts), Forestry, and IndustrialCraft 2, whereas many others are balanced versus vanilla (such as Mekanism, Tinkers Construct), and some that throw balancing out the window (Draconic Evolution).
> 
> Trying to balance a kitchen sink pack doesn't make it a kitchen sink pack anymore, instead its a hodgepodge of different mods cobbled together and a half-hearted attempt at making an intended progression path.
> 
> A method of removing permanent "progression breaking" buffs might be beneficial for those who are interested in seeing what a mod would be like from a fresh start, but it would still be up to them over what path they take.

I completely disagree.  The point of a kitchen sink pack is to have as many mods to play with as possible.  Not to let some mods stomp all over others.  Otherwise anyone could make a kitchen sink by just throwing mods together.  I would argue that leaving the mods as-is, is the "half-hearted attempt" as you put it.  It takes a lot more work to balance out a modpack, than it does to just throw mods together.  Think of it in a multiplayer environment.  You're insinuating that people should purposely avoid the better/more efficient/stronger mods their neighbors are using, if they want to experience another mod for the first time or how it was intended to be experienced.  That it's their choice to nerf themselves.  Sure, you could do that.  But where's the fun in that?  Everyone else will progress light years ahead of you, experience things entirely different, then either leave the server or stay to focus on building rather than available mods, because they've quickly powered through everything.  I really don't see how you could argue that it's better if people have the choice to shortcut everything, unless that's your own personal style of play?

You can balance a kitchen sink pack without forcing a specific line of progression btw.  Simply making X powerful thing require Y items that you can't get 'till you're at Z point, is usually enough to prevent people from rushing it.  Whether this means an item you can only get in the nether or the end, or even another dimension/planet.  Or maybe some kinda alloy that multiple mods can make but only once you've progressed pretty far in them.  Etc, lots of options.  That wouldn't be cobbling things together, that would be soft nerfing specific parts of specific mods so that they can't be used early game, but can be used later game to your heart's content.

> 
> 
> Your hand cannot be empty if you want to use veinminer/ore excavation. Rebind the key, and hold it down whenever you want to use it.
> 
> Believe it or not, I actually have balanced energy production extensively in Enigmatica 2, some of the options are far more OP by default. I really get that you'd like an "in-between" modpack, but I'm afraid I simply don't have the time or motivation to make it. Such a project would take at the very least 6 months to finalize.
> 
> I will work towards balancing Enigmatica 3 as much as possible when the time comes however :)

I must've read the manual wrong or something.  I coulda sworn it said that due to a bug, you can veinmine trees by holding down the key, even without a tool.

Anyway, if z64555 hasn't dissuaded you too much, I'll be looking forward to Enigmatica 3.  I do hope you consider a bit of balance work beyond just crazy OP stuff though.  Nothing too OCD.  It's just a lot more fun when you're unable to use 1 mod to beat 200 others, if that makes sense.

**Comment by z64555** [comment]
> I completely disagree. The point of a kitchen sink pack is to have as many mods to play with as possible. Not to let some mods stomp all over others. Otherwise anyone could make a kitchen sink by just throwing mods together.
Pretty sure that's how a lot of kitchen sink packs are. Mind you, not specifically the popular ones such as ATM1 and 2, but ATM3 starts making tweaks in the name of balancing that is quite frankly aggrevating.

Yes, some mods are indeed quite powerful compared to other. For example, Tinker's Construct is well beloved for its powerful tool system that can be customized to a particular need.  During its rise this however meant that many, if not all, mods that had tools with a particular unique attribute paled in comparison.  Why would you even use a tool from mod X if Tinker's did it better and/or cheaper?

But that doesn't mean that the recipes should be tweaked to make Tinker tools more expensive, or to have the other mods tools recipes tweaked so they be cheaper.  The player should be allowed to make their own choices on what they want to play with and be free to make their own decisions on what they like and don't like.  Remember, there are quite a few new players to modded minecraft now days, and tweaking the recipe in a kitchen sink pack will likely lead to misconceptions about the power/utility vs. cost of tools.

If, instead, a mod if far too overbearing for everything else in the pack to the point where it utterly annihilates progression, or, worse yet, makes things less fun, then the better option may be to take it out of the pack and put it a pack where it fits better.  (Tinkers is still quite powerful compared to many tools in mods these days, but it is also so popular that its almost impossible to omit.  Also because vanilla tools are very boring to replace after breaking your 5th iron pickaxe to do something so essential to the game)

> You're insinuating that people should purposely avoid the better/more efficient/stronger mods their neighbors are using, if they want to experience another mod for the first time or how it was intended to be experienced. That it's their choice to nerf themselves. Sure, you could do that. But where's the fun in that? Everyone else will progress light years ahead of you, experience things entirely different, then either leave the server or stay to focus on building rather than available mods, because they've quickly powered through everything. I really don't see how you could argue that it's better if people have the choice to shortcut everything, unless that's your own personal style of play?

It is each player's right to progress through the mods in their own time and own methods, to discover the strengths and weaknesses of each mod compared to others in an unadulterated form.  Blazing through the pack in the sake of progression is only impressive if your goal in life is to be a speed runner, my point here is to allow people to "stop and smell the roses" by the path if they wish to do so, and do not pressure them to go one way or another.

 
> You can balance a kitchen sink pack without forcing a specific line of progression btw. Simply making X powerful thing require Y items that you can't get 'till you're at Z point, is usually enough to prevent people from rushing it. Whether this means an item you can only get in the nether or the end, or even another dimension/planet. Or maybe some kinda alloy that multiple mods can make but only once you've progressed pretty far in them. Etc, lots of options. That wouldn't be cobbling things together, that would be soft nerfing specific parts of specific mods so that they can't be used early game, but can be used later game to your heart's content.

Changing the recipes of items breaks the intended progression of each mod, and can be a rather slippery slope once you start looking at using items from another mod to try to balance the recipe.  Alloys and fluids common to multiple mods in particular are a *really* bad place to do this, because said mods use them at different stages in their progression tree. For example, in some mods Aluminum is a mid- to late-game metal while in others its available as soon as you make a stone pick. Bronze is another example, being a fairly early/mid game alloy used in tinkers while being an essential material for Forestry. It is also a key ingredient in Industrial Craft 2 for the higher-tier Advanced Alloy/Mixed Metal ingots, and alloying bronze in IC2 is somewhat more involved than simply tossing in 3 copper ore and 1 tin ore into a smeltery (btw its ores -> dust -> crafted into alloy dust -> cooked into ingot)

Metals/resources unique to the mod is a safer bet, but it still changes the intended progression of the mod and gives a different experience.

.
> I must've read the manual wrong or something. I coulda sworn it said that due to a bug, you can veinmine trees by holding down the key, even without a tool.
Technically correct, you can veinmine trees with the quest book in hand, which isn't a tool.  Likewise you can do it with a stick, bone, or any item that is not a tool that can break blocks.

**Comment by MechanosG** [comment]
You're still chasing semantics.  Many modpacks nerf Tinkers, for good reason.  The most common nerf is to make the tool forge require later game materials, to block you from 2nd tier tools early game.  Some packs even don't include TC, although that's admittedly pretty rare when it comes to kitchen sink packs.  Just because it has a huge popularity though, doesn't mean it should be off limits, just because "someone" out there might want to use it in it's early access form.

The argument that if you don't want to use a specific mod, don't use it, doesn't apply because you can't choose for the pack to not have that mod in a multiplayer environment.  You can only choose to not use it yourself, which impacts your gameplay negatively if others do use it, or especially if other mods detect it and want you to use it, or otherwise interact with it.  As a random example, some mods use Steel as a gateway to further tech, and make you go to great lengths to create Steel.  But some mods make Steel super easy to make, breaking the progression for everything else.  This means you can skip the entire first half of the first mod by making Steel with another mod instead, then start off on the Steel stage.  Following your logic, you say it's more important to protect the integrity of the easy Steel mod, than it is to protect the integrity of many more mods affected by it.  That's illogical as it breaks more mods than it preserves.  Why would anyone realistically take the longer route, when JEI says you can make it another way, and when your neighbors are also taking the easy path?  How do you know what the original path even is, when you might not have played a mod by itself and aren't aware of how things are changed via interactions?

Devs don't design mods with the intention of them being balanced with every other mod.  That would take an insurmountable amount of work.  They do include compatibility with some mods sometimes, but for the most part they have their own idea of balance, and it varies greatly.  It is up to modpack creators to decide if they should be modified again, to better fit each other, or whether to just leave them as is.  Your argument is that by changing a mod away from it's original progress, you're somehow ruining that mod's progression and making it less fun.  My argument is that by including those unmodified mods, you're forcing imbalance upon other mods and breaking more progression than you preserve.  Your argument is you want an easy button, or feel other players should be entitled to their easy button, because it's "more fun" that way.  My argument is, that ruins the fun for everyone else.  I want more mods to be useful in the grand scheme of things, and feel players will get more enjoyment out of a consistent progression, rather than shorcuts through cross mod interaction.  You make it sound like I'm wanting something hardcore, when that isn't the case at all, and history shows that the most popular modpacks released over the years, are the ones that sculpt things to work better with each other, instead of just letting mods do whatever they want.

**Comment by z64555** [comment]
> The argument that if you don't want to use a specific mod, don't use it,

No, my argument is that if the mod is breaking progression of other mods to the point where it negatively impacts said mods, then it would be better to not include said OP mod in the pack altogether.  If people want to add the mod back into the pack on their own choice, that's up to then and they're free to do so, so long as they don't label their modified pack with the exact same name as their base. "Modified E2 pack" for example would be acceptable.

My other argument is that a kitchen sink pack is a pack that has a wide variety of mods together that are carefully selected to complement or serve as a counter-point to other mods within the pack.  When you start messing with the recipes the mods start to lose their integrity as an individual mod and instead becomes the part of the whole, rather than a sum of parts.

Lets use a cooking example.  Say you have bread, lettuce, tomato, cheese, pickles, mayonnaise, and mustard, plus some different slices of meats.  With a kitchen sink pack these are all there for the user to assemble to their liking while not needing to forage for the individual ingredients themselves.  This is a buffet, a kitchen sink modpack.

Now, lets say you take all those ingredients but decide people want the ingredients in a specific way or there's just some parts of that lettuce you think is too wilted. Oh, you also decided you have to cut the bread just so, because too much bread makes it unpalatable for the users. Oh, and you have to use so much mustard even tho people may actually prefer mayonnaise but you think more people like mustard instead. You also think people should get just the right amount of cheese (which some think is too much) only only one slice of tomato (but some people hate tomatoes while others like 3 slices) and 3 slices of pickles (when some people really like bread-and-butter pickles while others prefer a spear on the side).  You have invented a sandwich to your own tastes.

**Not everyone has the same taste as you do.**

That's not a kitchen sink pack, but rather a thematic pack.  YOU as a developer have a certain idea what the pack should be, even though the users can each have their own idea of what the pack could do better in or in fact could just toss the whole thing down the garbage bin because they didn't want tomatoes altogether.  Even the slightest tweak makes it less of a buffet and more of a salad or a sandwich, or a soup, some *very* minor changes are acceptable such as tweaking the power costs, adjusting the amount of mana, or resources it takes (but not adding different ingredients) to make a certain thing.  Too much adjustments to one thing or another gives you instead a soup of a salad, or a soggy sandwich that has too much bread and tastes like it was dunked in a pickle jar.  If you're going to resort to these sorts of changes, you have to do none, a *very* tiny amount, or go full tilt. There is no in-between.

ATM3 is a prime example of the soggy sandwich. It makes some *really* dumb balance decisions that force players to use another mod when they didn't really want to in the beginning, which is not the spirit of a kitchen sink pack but rather a poorly made thematic pack.  Whats more is that these balance changes are seemingly out of the blue, and nothing in the packs description prepares you for this other than maybe a brief tip to use JEI for recipe changes.  Folks that had wanted to learn everything about a particular mod have to immediately halt their progression because some bloke decided past this point is too high level and they should sample the other goods before proceeding.  That's like saying they can't eat their sandwich until they eat a piece of tomato that they specifically tried to avoid to begin with.

**Comment by MechanosG** [comment]
Are you suggesting that my suggestion should have been to remove a whole bunch of mods, instead of asking them to be better balanced?  How would that benefit anything?  People that want to play those mods, would get left out, just because you're setting some kind of standard that things should be left pure and unadulterated.

"Not everyone has the same taste as you do."  - That's such a hypocritical thing to say.  You started out saying 'Use some self control and don't use the mods you don't like, so that I don't have to exercise any self control and can use all the OP mods I like.'  But then you turn around and said "No, my argument is that if the mod is breaking progression of other mods to the point where it negatively impacts said mods, then it would be better to not include said OP mod in the pack altogether."

So...  are you saying you don't want mods to be modified, ever?  And if something is OP enough, don't add the entire mod to begin with, so that the people that like those mods, don't have to lower their expectations and/or work for it?  Despite you saying anyone that has a problem with the mods, can just choose to not use it?  When it could be you choosing to not use the modified mod?  Seriously, this whole argument has gotten silly and hypocritical beyond belief.

Just admit you personally prefer some of the mods in question, and want to see them unmodified in packs that include them, instead of trying to make a grand analogy that more choice is better, regardless of side effects.  Everyone has their preference and you're allowed yours.  Packs like that exist in the dozens however, which is why I'm suggesting different.

**Comment by z64555** [comment]
> Are you suggesting that my suggestion should have been to remove a whole bunch of mods, instead of asking them to be better balanced? How would that benefit anything? People that want to play those mods, would get left out, just because you're setting some kind of standard that things should be left pure and unadulterated.

No, I'm arguing against your suggestion with the reasons stated above, not "suggesting you have a different suggestion." You have a right to your suggestion to change E2 away from being a kitchen sink pack with tutorial quests to a tutorial themed pack or something else.

People that want to play those mods can convince the modpack dev to add them with some sound reasoning or list some possible alternatives.  Tinker's for example is a solid and very popular mod, but there are a few obscure mods out there that have a similar, if not as powerful, set of customizable tools.

> "Not everyone has the same taste as you do." - That's such a hypocritical thing to say. You started out saying 'Use some self control and don't use the mods you don't like, so that I don't have to exercise any self control and can use all the OP mods I like.' But then you turn around and said 
>>"No, my argument is that if the mod is breaking progression of other mods to the point where it negatively impacts said mods, then it would be better to not include said OP mod in the pack altogether."

> So... are you saying you don't want mods to be modified, ever? And if something is OP enough, don't add the entire mod to begin with, so that the people that like those mods, don't have to lower their expectations and/or work for it? Despite you saying anyone that has a problem with the mods, can just choose to not use it? When it could be you choosing to not use the modified mod? Seriously, this whole argument has gotten silly and hypocritical beyond belief.

Mods in a kitchen sink should not be modified by pack devs to a major degree.  This "major degree" means the recipes and progression tree to acquire key items and blocks are significantly different from the original recipe, most notably by using materials from other mods.  For example, say you want to use some entry-level EnderIO power conduits, but the recipe was tweaked for "balance reasons" to use resonant flux ducts.  For some reason (such as the resonant flux ducts being able to transmit more RF/t than the entry-level conduits), you won't want to progress down the TE progression tree just to get resonant fluxducts for your conduits, and would rather use some other method.  Now, repeat this experience with a dozen other wonderful surprises and you'll quickly come to hate the pack.

As I've stated in the previous sandwich example, once you do modify things the pack ceases to be a kitchen sink pack and becomes a themed pack.  Yes, this is a argument over semantics of what a "kitchen sink" pack is.  Some tweaks that are acceptable are power output from generators or number of items obtained from a craft, such as 8 products instead of 4, or vice versa, is acceptable so long as the original recipe is virtually unchanged.  Once the pack is themed, mods can (and most likely should) have their recipes tweaked to whatever fits the theme in a reasonable manner.

> Just admit you personally prefer some of the mods in question, and want to see them unmodified in packs that include them, instead of trying to make a grand analogy that more choice is better, regardless of side effects. Everyone has their preference and you're allowed yours. Packs like that exist in the dozens however, which is why I'm suggesting different.

You've missed a key thing that differentiates Enigmatica 2 from most of those "packs that exist in the dozens." Tutorial quests.  There are a number of quests in E2 that took some significant time by the authors in creating and editing, and actually line up quite well with the individual mods they are showcasing.  This is what I believe kitchen sinks should try to do to make them stand apart from others, to use quests in a tutorial standpoint or even in a story-telling fashion to bind the mods together in a way that the user wants.

**Comment by MechanosG** [comment]
You're going back to semantics again.  You're assuming "kitchen sink" means everything has to be untouched, which in reality the term comes from "everything but the kitchen sink".  This doesn't imply "everything unchanged" or "everything EXCEPT modpack specific modifications".  That's just your definition and preference.  It implies a whole bunch of mods, and that's it.

While you do have a point that Enigmatica 2 has a nice quest system that feels pretty different from the norm, that is unrelated to balancing and is just you dodging your preference again.  I agree, that the addition of such features are a good thing, and also a selling point.  But you can have the fancy quests, while still rebalancing OP mods.  E2 Expert does just that.

I haven't actually heard a single good reason to not balance out a kitchen sink pack.  Look at FTB Ultimate, that was one of their most popular packs of all time.  If it's properly balanced, recipe changes are only a minor inconvenience and fits with the other mods in the pack.  Again, I'm not saying things need to be gated behind 10 nested recipes, sending you through a tunnel of 3-5 other mods that you don't want to play with.  That's a bit on the hardcore side, and Expert already kinda does that.  My suggestion simply wished for a middleground, as lately there's been a lot of modpacks that don't even try.  I'm also interested partially because a modpack I was working on, ran into a wall.  So I'd love to see someone else make something similar.

**Comment by MechanosG** [comment]
Ok, lemme change the narrative then.  Does it matter if it's labeled a "kitchen sink"?  A lot of packs don't even use that term, even if they fit the description, even your version of it.  If it matters that much to you, lets just drop the label then and pretend my suggestion is for a themed pack.  Do you still have a problem with lightly balancing out mods so they can be enjoyed in the same pack, without shortcutting each other's progression?


> "followed by opinion that if the modpack dev does such a thing, they had better be prepared to go the full distance by modifying more and more items to fit the theme, otherwise it runs the risk of being a pack with annoying recipe changes that interrupt the progression too much."

Well that's your opinion.  Many packs have worked without having to do that.

> Kitchen sink packs are popular, because it can be initially made as easily as just tossing together a bunch of mods and having a go at seeing if they play well together. Often new pack devs such as yourself hit a wall or lose track of what they wanted to do, or maybe are actually satisfied with how their pack turned out and just leave it there. But to get a good pack together requires play testing of the mods to see if they actually do play well together, and if they don't or if they cause a bunch of problems for hosting, then they get removed from the pack's later versions.

Lol no, kitchen sinks are not popular because they're easy to make.  They're popular because they have a lot of mods that work together, something that isn't easy to do.  You have to resolve conflicts.  You have to resolve requirements like forge versions.  You have to choose what world generation to use if there's multiple, and have to try and prevent cascading loops.  The more popular kitchen sink packs are the ones that have gone beyond the average, making tweaks here and there to ensure compatibility.  By your definition, E2 isn't a kitchen sink because NillerMedDild actually did balance energy production stuffs and said so earlier in this thread.  Lets just give the semantics a rest.

Btw my current modpack project is like my 5th.  By your definition it isn't a kitchen sink at all, because it's not just mods thrown together.  The biggest feature is completely custom ore gen using a 3rd party ore mod, making semi-realistic ore veins based on real world geology.  Multiple ore types in each vein, etc.  Kinda like GT5 oregen, only closer together and without cascading worldgen.  After a lot of time creating the veins and doing geology research, I discovered the ore mod was using up way more tick time than it should have been, scaring me into thinking I could be wasting my time because it'll end up lagging too much for on the fly new chunk generation to be possible without lagging other players.  However, overall minus a few rare features you don't see in packs often, it feels a lot like E2, only with the more OP mods being slightly gated to fall in line with the rest of the pack.

> It is far too easy to try to start changing things in mods within the modpack "for the sake of balance" and then lose track of what exactly you're trying to accomplish.

That's probably true.  But that's no reason to not attempt it at all.  It just means some people have taken it too far.  I mean, I feel like somewhere under your thick skin of semantism and need for labels, you want the same thing I do.  You don't want the experience to be so muddled with that it's no longer fun.  I don't want that either.

**Comment by z64555** [comment]
Alrighty, I'm just gonna stop the argument here because we'll just end up in an echo chamber with me repeating the same things I've said over the past few narratives.  If you would have perhaps stopped spending effort into trying to attack my character with comments such as "under your thick skin of sematism" you perhaps would have realized that I have stating these things all along:

* Kitchen sink packs are packs that have a wide variety mods that are selected to complement and or serve as a counterpoint to each other.
* Kitchen sink packs should not have any major editing done to the recipes of their participating mods because:
  1. You, as a developer, have your own ideas while the players have their own ideas of what "balance" means.
  2. If you, as a developer, do not know what your theme is or what your goal is other than "to balance things" is, there is a high chance of going too far and muddying the progression tree for all affected mods.
  3. Balancing a recipe using items from a different mod entirely should not be in a kitchen sink pack, because that is what is part of what makes a themantic/themed pack.  In addition to statement 2, players who are not prepared or unwilling to go through all the mods in the pack may not like this balancing act altogether.
* Kitchen sink packs could attempt balancing through more subtle methods such as:
  1. Adjusting the power output of generators
  2. Adjusting the power input of consumers
  3. Adjusting the number of items the crafts give.


Although I have not stated this before, I do agree with a 4th option for balancing:

* Adjusting the materials used to make a certain item to use a material that is accessible later within that mod. 

An example would be requiring the tool forge from Tinker's to use alloy blocks only, Nether metals, or perhaps use a specific metal that has an ore at a specific mining level.

On a final note.  Nowhere have I stated that you or anyone must obey my suggestions. Everyone is free to do as they please and have their own experiences.  My arguments here are from personal experience with modded minecraft over the years and are stated as such to try to dissuade you from certain things.

**Comment by MechanosG** [comment]
> Alrighty, I'm just gonna stop the argument here because we'll just end up in an echo chamber with me repeating the same things I've said over the past few narratives. If you would have perhaps stopped spending effort into trying to attack my character with comments such as "under your thick skin of sematism" you perhaps would have realized that I have stating these things all along:

I'm not attacking your character, I'm pointing out how you contradict yourself, then assert that your definition is the only true meaning, when you do not get to decide that.  And even if it were true, I was willing to say "Fine, lets not call it a kitchen sink." and you're still going on a tangent.

>     * Kitchen sink packs are packs that have a wide variety mods that are selected to complement and or serve as a counterpoint to each other.

Yes.

>     * Kitchen sink packs should not have any major editing done to the recipes of their participating mods because:

No.  You do not get to decide this.  This is 100% your preference.

>       1. You, as a developer, have your own ideas while the players have their own ideas of what "balance" means.

The dev gets to decide how a pack is made, just like a mod author gets to decide how they design their mod, and a player gets to decide what types of modpack they want to play.  If a dev makes a pack that is disliked by a majority, less people will play it.  It's that simple.  But you do not get to decide what or how they make it, you only get to decide if you play it or not.

>       2. If you, as a developer, do not know what your theme is or what your goal is other than "to balance things" is, there is a high chance of going too far and muddying the progression tree for all affected mods.

It's certainly possible, but no, you can't just say "Oh, you might not make something I'll like, so just don't even try, because I know what's best."  People try out new ideas.  Some are liked, some aren't.  That's innovation.

>       3. Balancing a recipe using items from a different mod entirely should not be in a kitchen sink pack, because that is what is part of what makes a themantic/themed pack.  In addition to statement 2, players who are not prepared or unwilling to go through all the mods in the pack may not like this balancing act altogether.

Again with your semantics.  Like I said, if it will make you happy, call it a theme pack, even if that's "not" what it is.  Just because you don't want to have to use another mod, doesn't mean 10 others won't mind it.  Why are you even playing packs that have mods in it that you don't like?  One of the more popular packs semi-recently was FTB Continuum, and I absolutely could not play it.  That doesn't make it a bad pack, that just means I didn't like it.
 
>     * Kitchen sink packs could attempt balancing through more subtle methods such as:
>       
>       1. Adjusting the power output of generators
>       2. Adjusting the power input of consumers
>       3. Adjusting the number of items the crafts give.

How is that different than a changed crafting recipe?  If you change how a machine works to the point that it acts just like a machine from another mod, why is it so important to you that every mod only interact/require items from itself?  Sounds a lot like you're trying to recover your argument by now including E2 in your description of a kitchen sink btw.
 
> Although I have not stated this before, I do agree with a 4th option for balancing:
> 
>     * Adjusting the materials used to make a certain item to use a material that is accessible later within that mod.
> 
> An example would be requiring the tool forge from Tinker's to use alloy blocks only, Nether metals, or perhaps use a specific metal that has an ore at a specific mining level.

This is exactly my proposed suggestion, that you've been arguing against.  With the exception that I did say I was willing to hop around in between mods if needed.

> On a final note. Nowhere have I stated that you or anyone must obey my suggestions. Everyone is free to do as they please and have their own experiences. My arguments here are from personal experience with modded minecraft over the years and are stated as such to try to dissuade you from certain things.

So that's your insurance policy.  You say things are a certain way, but then say "No actually, you're free to do or think whatever you like, so don't mind me."

Look, I tried to meet you half way, and you're still choosing to say it's your way or the highway, then basing all of your argument on the label "kitchen sink", then aren't even willing to let me call it something else.  So I'm going to continue this conversation with anyone that's interested, but don't be offended if I don't let you bully the conversation in your favor.  If you have a constructive argument other than "they might overbalance it or make me use a mod I don't want to use right now, so it's not worth it", then by all means.  That argument is noted.

**Comment by donnymoonshine** [comment]
Stumbled on this looking for more expert mode packs to play anything come to mind I realize this thread is like two years old

**Comment by CactusCool** [comment]
@donnymoonshine It depends on what you like if you like gregtech I highly recomment omnifactory or ftb interactions if you like simmilar packs to e2e I reccoment Project ozone 3 either titan or kappa, all the mods 3 expert is also another good choice

**Comment by Njord89** [comment]
> Alrighty, I'm just gonna stop the argument here because we'll just end up in an echo chamber with me repeating the same things I've said over the past few narratives. If you would have perhaps stopped spending effort into trying to attack my character with comments such as "under your thick skin of sematism" you perhaps would have realized that I have stating these things all along:
> 
> * Kitchen sink packs are packs that have a wide variety mods that are selected to complement and or serve as a counterpoint to each other.
> * Kitchen sink packs should not have any major editing done to the recipes of their participating mods because:
>   
>   1. You, as a developer, have your own ideas while the players have their own ideas of what "balance" means.
>   2. If you, as a developer, do not know what your theme is or what your goal is other than "to balance things" is, there is a high chance of going too far and muddying the progression tree for all affected mods.
>   3. Balancing a recipe using items from a different mod entirely should not be in a kitchen sink pack, because that is what is part of what makes a themantic/themed pack.  In addition to statement 2, players who are not prepared or unwilling to go through all the mods in the pack may not like this balancing act altogether.
> * Kitchen sink packs could attempt balancing through more subtle methods such as:
>   
>   1. Adjusting the power output of generators
>   2. Adjusting the power input of consumers
>   3. Adjusting the number of items the crafts give.
> 
> Although I have not stated this before, I do agree with a 4th option for balancing:
> 
> * Adjusting the materials used to make a certain item to use a material that is accessible later within that mod.
> 
> An example would be requiring the tool forge from Tinker's to use alloy blocks only, Nether metals, or perhaps use a specific metal that has an ore at a specific mining level.
> 
> On a final note. Nowhere have I stated that you or anyone must obey my suggestions. Everyone is free to do as they please and have their own experiences. My arguments here are from personal experience with modded minecraft over the years and are stated as such to try to dissuade you from certain things.

You "lost" that argument after your first post and are very desperatly trying to "win".  Most kitchen sink packs do already balance recipes and thats what they should do, else i could just slap some mods together and call it a day.  Arguing with people like you is one of the things that drives me most crazy.

**Comment by NillerMedDild** [comment]
I'm just gonna lock this issue because of negativity.
