### ISSUE TITLE
Recipes randomly stop working

### ISSUE THREAD

**Issue by erplsf** [NillerMedDild/Enigmatica2Expert#40]
#### Issue Description
After some time recipies stop working in the crafting table/bench. Client restart solves the issue.
https://imgur.com/a/1QBWY8S
#### What you expected to happen
I expected to craft an item.
#### Modpack version (Do not use "latest")
1.20
#### Your most recent crash report or log file where the issue was present
https://paste.ee/p/tjjsh

**Comment by NillerMedDild** [comment]
Does it happen in vanilla crafting tables aswell?

**Comment by erplsf** [comment]
Yes.
![2018-04-30-161533_1920x1080_scrot](https://user-images.githubusercontent.com/4072364/39428914-c7ce1b0e-4c91-11e8-9b3a-200356b70834.png)

**Comment by erplsf** [comment]
Also, it seems like it is some variants of the recipies are broken:
![2018-04-30-162416_1920x1080_scrot](https://user-images.githubusercontent.com/4072364/39429261-04f8e5d0-4c93-11e8-8d29-cd7b7f1b9a27.png)
![2018-04-30-162406_1920x1080_scrot](https://user-images.githubusercontent.com/4072364/39429262-055e641e-4c93-11e8-8ca8-a1b591937a83.png)

**Comment by NillerMedDild** [comment]
Interesting. I haven't seen anything like this since the first week of 1.12 :P

Could you try replicating it with some of the custom recipes?

**Comment by KitanaShaw** [comment]
I have the same issue what i noticed it only happens with IC2 recipes

**Comment by NillerMedDild** [comment]
Are you using SpongeForge @KitanaShaw?

**Comment by KitanaShaw** [comment]
nah i downloaded the the pack zip from curse forge and run it through MultiMC

**Comment by NillerMedDild** [comment]
I'm afraid I don't know what's causing this issue.

**Comment by KaneHart** [comment]
This *sheep* Is driving me insane. This is happening to me none stop in Single player. The only fix for it is to reboot the entire game. Relogging does not fix it at all.

I had issues with Pouring Iron to make Iron Plates on casts but could use clay till I rebooted the game.
Now I could not make simple IC2 copper insulated wires. I even relogged no luck. So I had to reboot the entire game again and boom it fixed it. 

As someone who records this in 1 shot I'm pulling hairs out lol

**Comment by KaneHart** [comment]
Sadly this issue hit my nerv today and I think I'm done till it's resolved. I sadly started uploading episodes so people are going to kill me :(.

Here is the bug after just restarting having the Copper Insulated Cable Bug.
![4oowu11](https://user-images.githubusercontent.com/425853/39537590-11e5e8bc-4e08-11e8-92ce-24555cd1c99e.png)

Here is that Video it's little over 2 Minutes you can see how this would drive anyone insane...
https://www.youtube.com/watch?v=2bRAdpdymGQ


So far the only thing I do that could cause issues is I pause a lot and I tab during loading of the world as well. If there is a break there maybe someone can test it out themselves...

This is Single Player keep in mind.

My best guess is CraftTweaker is it called these days. You had an update recent maybe read the change logs for version CraftTweaker2-1.12-4.1.7

This is Interesting and Old but it's funny because it's different then what our issue is but I loved the description of the bug
"They sometimes do, but somehow the behavior changes on each restart."
I wonder if something like this is happening with recipes in another section of code?
https://github.com/CraftTweaker/CraftTweaker/issues/448


Other People who posted this bug:
https://github.com/NillerMedDild/Enigmatica2Expert/issues/47
https://github.com/NillerMedDild/Enigmatica2Expert/issues/45

**Comment by NillerMedDild** [comment]
None of the recipes that are failing are made with CraftTweaker, they're exclusively from IC2 and Tinkers' Construct.

I need your latest.log, please.

**Comment by NillerMedDild** [comment]
I made a bug report on the IC2 issue tracker:
https://bt.industrial-craft.net/view.php?id=2365

**Comment by NillerMedDild** [comment]
Well the recipe handler for IC2 shaped and shapeless recipes is very different from the one that handles casting in Tinkers' Construct. I think it's more likely we're looking at a weird desync issue here.

**Comment by NillerMedDild** [comment]
The common denominator for the 3 of you is MultiMC - Could you move your save to a Twitch instance and see if the bug persists?

**Comment by peterix** [comment]
I cannot reproduce this after about 2 hourrs of gameplay on 0.22.

I also don't see how this could be in way specific to MultiMC...

Basically, ¯\_(ツ)_/¯

**Comment by NillerMedDild** [comment]
Me neither ^^'

**Comment by NillerMedDild** [comment]
... Come to think of it, it's probably the fresh install that fixed the issue in KaneHart's case. Didn't think of that for some reason.
