### ISSUE TITLE
Removed the mod Wireless Charger

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#444]
It was added before other Wireless Charging means were updated to 1.12.2

**Comment by nullKomplex** [comment]
If I'm not mistaken, there is nothing even close to a suitable replacement to the personal charger from any mod in the pack. Is it intentional that there is no way to replicate that behavior now? I could see simply disabling the regular wireless charger as it is now redundant. On the other hand there's a solid argument for the personal charger being OP.

**Comment by NillerMedDild** [comment]
The replacement for the Personal Charger will be added later on, see https://github.com/NillerMedDild/Enigmatica2Expert/issues/407 :)
