### ISSUE TITLE
We need to do more with Bee's. Their quite useless.

### ISSUE THREAD

**Issue by KaneHart** [NillerMedDild/Enigmatica2Expert#486]
If it's hard to configure and go through I can understand that. Might break some progression. But I'm finding this pack is lacking really bad in Bee's in fact Gendustry is really useless because there is really nothing much bee's are worth being used sadly. 

There is quite a few Bee Mods so I just wanted to hear your overall thoughts on it.

Thanks.

**Comment by NillerMedDild** [comment]
It would be very tedious to add a bee mod, because I'd have to go through and modify nearly all bees, and make sure they can't be bred before a certain point in the pack.

One of the selling points of E2E is that bees can be bypassed almost entirely, which is rare for an Expert themed pack.

The normal pack does however have an abundance of bees :)
