### ISSUE TITLE
Crash On Load - Astral Sorc Related?

### ISSUE THREAD

**Issue by RebelliousUno** [NillerMedDild/Enigmatica2Expert#526]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crash on load

**Modpack version (Do not use "latest")**
1.4.9

**Logs**

https://pastebin.com/kYDkmycp

**Screenshots**

N/A

**Additional context**

1.4.6 Works -> Anything higher seems to fall over

**Comment by NillerMedDild** [comment]
The `forge` config in the config folder has an option for removingErroringTileEntities, set that to true and load up your world :)

**Comment by NillerMedDild** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/963

**Comment by NillerMedDild** [comment]
Remove the block at `-19,57,26`, or wait for yet another hotfix :)

**Comment by HellFirePvP** [comment]
Uh... Sorry for the metric ton of hotfixes lately.. xP
Turns out if you touch on a lot of features, lots of mods hand you stuff you wouldn't expect since lots of mods carry over old legacy code xP

**Comment by NillerMedDild** [comment]
No worries - I feel like you should mark the hotfixes as beta or alpha at this point though :P

**Comment by HellFirePvP** [comment]
Uh... i don't necessarily expect things like these to break... :P Cause i'd expect mods to follow standards as they are presented in forge - in this case either using the FakePlayer class, a subclass of that, or a subclass of FakePlayer's superclass EntityPlayerMP. Ic2 does none of all that. If mods followed standards, maybe this wouldn't be necessary. Not sure if i'm gonna mark the update that contains the fix for this alpha or beta as i'd think after this it is/might be stable; not sure when the next bit pops up though...

**Comment by RebelliousUno** [comment]
> The `forge` config in the config folder has an option for removingErroringTileEntities, set that to true and load up your world :)

Thanks I'll give that a go

**Comment by RebelliousUno** [comment]
fwiw I haven't made any sort of start with Astral Sorc 
Just updated to 1.4.9, set the config and loading the pack.
Fingers Crossed

**Comment by RebelliousUno** [comment]
That seems to have sorted it thanks

**Comment by HellFirePvP** [comment]
Fixed on IC2's side with version 2.8.106-ex112 on curseforge.

Just as a heads-up.

**Comment by NillerMedDild** [comment]
Thanks for letting me know.
