### ISSUE TITLE
Small Plate Press Improvements

### ISSUE THREAD

**Issue by SupportMyNut** [NillerMedDild/Enigmatica2Expert#753]
When using the Small Plate Press from Advanced Rocketry, the blocks get turned into Vulpes Library plates making them unusable in any recipes other than the dense plate in the IC2 compressor.

**Comment by MorganSimic** [comment]
I just tested changing the output in the AR xml recipe files from libVulpes plates to thermal plates for the block to plate recipes. That did create the porper output but JEI still shows duplicate recipes wich still output the libVulpes plates. So i think something other than AR is interfering here. Of course i didn't test what the actual output of that recipe is in the end. Dummy me.

**Comment by NillerMedDild** [comment]
useDefault needs to be set to false, otherwise the recipes will be loaded from the Jar directly: Meaning the LibVulpes plates will still be processed. The following tasks need to be done:

- [ ] Convert all blockMetal -> plateMetal recipes to Thermal Foundation output.
- [ ] Re-add all oreMetal -> dustMetal recipes
