### ISSUE TITLE
Creative Gas Tank Frame & Master Trophy Model Bugs

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#763]
The models are messed up, as C&B seems to use item IDs, which can (and often does) shift from world to world.

**Comment by ben-mkiv** [comment]
i would suggest to not use c&b at all for the trophy/creative drawer recipe. 
I've placed mine and its now a useless piece of trash as the item data changes, and/or it can be placed so that it splits in up to 8 different blocks...

Even a chiseled block of iron is closer to the NBT data of the master trophy than my trophy is now -.-

**Comment by MaxNeedsSnacks** [comment]
Honestly, @NillerMedDild, we should consider switching to ContentTweaker for these two ^^ There are just too many bugs

**Comment by NillerMedDild** [comment]
True ><

**Comment by MaxNeedsSnacks** [comment]
Welp, have fun modelling the blocks :P (or just make them items)

**Comment by NillerMedDild** [comment]
Probably just gonna go with items, or even add the Trophy mod just for the this :P

**Comment by ben-mkiv** [comment]
c&b has a command (`c&b.exportmodel`) to export the item you are holding to json format, which looks like to be supported by contenttweaker, but havent tried this on my own yet

**Comment by MaxNeedsSnacks** [comment]
Wait, doesn't the TF master trophy still need to be fixed after bc470b?
