### ISSUE TITLE
Losing health on login

### ISSUE THREAD

**Issue by siber-cat1** [NillerMedDild/Enigmatica2Expert#799]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Whenever I log in to my singleplayer world, my current health is reduced to 124.0 points of my 358.6 point maximum. Health recovers just fine once logged in.

**Modpack version (Do not use "latest")**
1.54, plus the Health Bar and Just Enough Calculation mods
I've got a few convenience/decorative mods disabled, and can provide a list if you need it

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

I'll admit, I went a little crazy raising my max health. I've got most of the Spice of Life hearts, Botania's Ring of Odin, and almost all the max health boosts from Astral Sorcery's attunement perks, the last of which is my main suspect as the cause of the problem, due to the roundness of my health when I log in.

**Comment by NillerMedDild** [comment]
I think this is caused by the health limit set, AS has to override it again on each login. I'll see if setting it to something silly works.

**Comment by OmaiGrundles** [comment]
I would like to confirm this issue, every time I load my health gets cut to a fraction of its max. I believe it may be possible to get max health past 1000 in this pack (I've really been trying because I want to brute-force the chaos dragon) so setting the max health to 2000 should stop this issue from happening no matter what, if that's the root cause.

**Comment by NillerMedDild** [comment]
Should be fixed :)
