### ISSUE TITLE
Switch Mekansim version to DZ Fork

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#914]
The new fork fixes a host of issues we're having.
https://minecraft.curseforge.com/projects/mekanism-dz-edition

**Comment by Tntdruid** [comment]
Looks good 👍

**Comment by xob** [comment]
Not sure if this is an appropriate place for this question, but will changing to the DZ fork fix the Digital Miner's inability to find / mine Destabilized Redstone Ore?

I know it fixes a lot of things, but I wasn't able to find any information about this particular issue.

**Comment by NillerMedDild** [comment]
I think you need to set the DM to Fuzzy mode.

**Comment by xob** [comment]
Really good suggestion, but unfortunately it doesn't work. I silk touched one to add an ItemStack filter with Fuzzy turned on (instead of using an oredict filter like I typically use), and the DM still could not find a single one.

I tried the DZ fork, and the problem is there also. I'll create a separate issue for this.

**Comment by fajcyk** [comment]
Mekanism author became active again: https://minecraft.curseforge.com/projects/mekanism/files
I noticed switch to the fork caused some issues (mostly with quests, but not only), I don't know if it would be worth to switch again (since I didn't check if it fixes issues that led to the switch) but just putting that out there.

**Comment by NillerMedDild** [comment]
Turns out the quest issues were caused by Better Questing :P 

We will be reverting to regular Mekanism, thanks for the info :)
