### ISSUE TITLE
Crash with Psi

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#94]
#### Issue Description
The game crashes when i try to use the rod of the Psi mod
#### Modpack version (Do not use "latest")
Modpack Version 1.26c
#### Crash Report
https://pastebin.com/cMRSrVWK

**Comment by Angelos33** [comment]
So far only with the gold focusing rod. i haven't tested any other.

**Comment by NillerMedDild** [comment]
Only the rod? You didn't assemble it?

**Comment by NillerMedDild** [comment]
How did you try to use it? For what?

**Comment by Angelos33** [comment]
Please I AM NOT AN IDIOT. I assemble it and the i tried to press the key to select a spell and it crashed.

**Comment by Angelos33** [comment]
well apparently i am talking with one!!

**Comment by Lukas45** [comment]
Either way, outside of being rude, tell Twitch to use the Jar launcher instead of Native. There's a chance that may fix it (probably wont).
Besides that, we need to know the following:
* All parts of the rod (because you only mentioned 1)
* The spell used
* Does it loop crash you, or only when used?

You know, stuff that should have been mentioned from that start, because a LOT of people have never played with Psi.
You don't go to a mechanic either and say "Car doesn't turn on when I put the key in, fix it!!"
Information is needed!

**Comment by Angelos33** [comment]
Aside of being rude, cause i wasn't the one that started it. If that was your first response then there would be no rudeness from my side.
Now as for the crashes. I made the gold rod frame(4 gold ingots, 1 oak wood) and then i assemble it in the rod constractor to start with the mod psi. After that i make my first stack of psidust and then i smelt the psidust in the smeltery to make psimetal ingot. After that i made a second gold rod frame and then i assemble it in  the rod constractor with the basic parts( humble rod crux, minor rod notch, glowing rod source, white rod varnish). i didn't make any spells yet and i equipt it in the hand and pressed the key to select a spell( haven't made any yet it should just open the menu with no spells) and then i crash. it kicks me out of the game. 
if any more information is need it i shall provide them just asking like i am an intelligent human that have reported many bugs to help the pack is enough.

**Comment by Lukas45** [comment]
It's always best to assume it's a user-based error, because 90% of the time, it is (taking in general from both Github and Discord submissions), and based on your first info, we had no reason to believe otherwise.
Psi isn't used by a lot of people, so many are clueless with it, and can cause random crashes from the most random things.

I will test it out later today, and likely form a crash report on the Psi github if I can replicate it

**Comment by Angelos33** [comment]
i get it cause i am a programmer myself but even if we assume that is a user based error being polite is always nice. Especially with the ones that try to help. if you see all the previous reports i made was accurate.

**Comment by Lukas45** [comment]
I don't really check the history of every person who makes a submission. And you did start out with accusing us of thinking you were an idiot (by asking for more info), at least that's how I saw it, because we have to assume what you're doing based on the info given (which wasn't much TBH). Unknowing =/= Idiot.
But, that's all misunderstandings, and there's probably not much reason to continue this discussion.
I will look into the matter in some hours, and maybe ask more questions

**Comment by NillerMedDild** [comment]
I didn't mean to be rude, my apologies :)
I'll try to replicate it again asap.

**Comment by NillerMedDild** [comment]
I can't seem to reproduce it. What's your Psi level, and did you Load the level from a previous instance?

**Comment by Angelos33** [comment]
Yeah me neither. I was level 0 at the time if the crash. No i didn't load anything from previous instance. It seems it's gone now. I moved on to level 16 without any crash. I don't know what that was but it didn't happen again. If no one else have this crash then you can close this issue. 
Thank you for look into it.

**Comment by NillerMedDild** [comment]
Weird, but nice it seems fixed!
