### ISSUE TITLE
Add Decondensentrator recipe for NC Sulfuric Acid

### ISSUE THREAD

**Issue by blichte1** [NillerMedDild/Enigmatica2Expert#952]
**Modpack version**
1.57
**Can the issue be reproduced?**
Yes.

**Logs**
N/A
**Issue**
This is a repeat of the issue #772. Identical problem, I guess because of the update to the latest version of mekanism. There have been other knock-on effects as well from the upgrade, e.g.: was the shrinking of the size of the Ultimate Induction cell intentional?

**Comment by NillerMedDild** [comment]
Thanks for the report. The shrinking was not intentional, what value was it and what is it now?

**Comment by blichte1** [comment]
Interestingly, I just restarted the pack and the shrinking issue seems to have resolved itself. It had become 51.6 (or something around there, maybe 52.6) and has now returned to the original value of 204.8. ... Very odd.

**Comment by NillerMedDild** [comment]
O_O
I'm gonna ignore that for now :P

**Comment by blichte1** [comment]
Yeah, that's probably for the best...

**Comment by MaxNeedsSnacks** [comment]
Okay, so I discovered the following:

- The two are interchangable using the Fluid Dict converter
- The Mekanism one does not have a bucket form (which makes sense since sulfuric acid attacks iron)
- There is currently no way to decondensentrate NC sulfuric acid
- As per usual with NC liquids that have Mek gas forms, NC is able to convert them on the fly, meaning you can extract Mek Sulfuric Acid gas using Pressurised Tubes or Gas Conduits from NC machines.

For now I'll be changing the topic of this issue to NC sulfuric acid not being decondensentrated, which is something I might add later. Cheers!

**Comment by MaxNeedsSnacks** [comment]
Just found out that there's apparently no way to add (De)-Condensentrator recipes as of now unfortunately, so I don't think this can be fixed rn.
