### ISSUE TITLE
IC2 RTG exploit?

### ISSUE THREAD

**Issue by Krapht** [NillerMedDild/Enigmatica2Expert#990]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
I don't know if it is intended or not but...
1) Block of blutonium requires 3 tiny **ic2** plutonium (no substitutions afaik)
2) 3 blutonium can be used to make an ic2 RTG as an alternative to the ic2 big plutonium
3) The ic2 RTG can be thermal Centrifuged to get 3 (big) ic2 plutonium back
4) (big) plutonium can be crafted to 9 tiny 

So 3 tiny plutonium can by crafting+processing be converted to 9 blutonium -> 3 RTGs -> 9 big plutonium -> 81 tiny plutonium

**Comment by MaxNeedsSnacks** [comment]
That's definitely an interesting process, but I **think** the other ingredients for Blutonium (Cyanite Blocks, Empowered Lapis, etc) kind of balance that out. I can always remove the Blutonium to RTG recipe if Niller wants to though ^^

**Comment by Krapht** [comment]
It all depends if you want the players to keep ic2 reactors running or not =)

From what I can tell, the only usage for ic2 RTGs are very high-end crafting recipies (tier  6 ore miner / solar controllers and two creative items) and the standard use in a ic2 radioisotope machines. But at that point I'm not sure how much benefit the radioisotope machines will provide.

**Comment by NillerMedDild** [comment]
I'm tempted to leave it in as an Easter Egg to be honest :P

**Comment by MaxNeedsSnacks** [comment]
Even though this is definitely not intended, the cost of the other materials for Blutonium sort of balances this out ^^

**Comment by Luspuz** [comment]
I've also found this exploit, I think this should be fixed because it discourages the use of fission reactors (ic2 or nuclearcraft) to create plutonium, which require hours (ic2), or minutes if parallelized with many fission reactors in nuclearcraft (each mox fuel depletes in 83 minutes), while the RTG exploit only requires seconds (if you have everything automated for blutonium, and I think everyone has at this stage of the game). You may only remove the thermal centrifuge recipe of RTG -> plutonium. 

p.s. Best modpack I've ever played so far :)

**Comment by Kuktar** [comment]
I agree if I get a vote

**Comment by NillerMedDild** [comment]
Good point, we'll remove the exploit.

And thanks! :)
